// packages/website/src/lib/components/chat/Message.svelte
<script lang="ts">
	import type { UserWithRoles } from '@core/model';
	import type { Message } from 'ai';
	import Cross from '../branding/Cross.svelte';
	import Avatar from '../user/Avatar.svelte';
	import ResponseSources from './ResponseSources.svelte';

	export let chatId: string | undefined;
	export let message: Message;
	export let prevMessage: Message | undefined;
	export let user: UserWithRoles;

	const { id, content, role } = message;
</script>

<div
	class="flex flex-row items-center w-full px-2 py-4 overflow-x-hidden bg-white border border-t-slate-300"
>
	<div class="flex flex-col content-start">
		{#if role === 'user'}
			<Avatar {user} size="md" class="border shadow-lg" />
		{:else}
			<Cross />
		{/if}
	</div>
	<div class="flex flex-col w-full pl-5 pr-3 overflow-x-clip">
		<div class="w-full break-words whitespace-pre-wrap">{content}</div>
		{#if role !== 'user'}
			<ResponseSources aiResponseId={id} {chatId} />
		{/if}
	</div>
</div>

// packages/web/src/components/chat/Message.tsx
"use client";

import { Avatar } from "@components/user";
import { squareDimensionClasses } from "@lib/sizing";
import { Message as ChatMessage } from "ai/react";
import { TbCross } from "react-icons/tb";
import { ResponseSources } from "./ResponseSources";

export function Message({
  chatId,
  message,
  prevMessage,
}: {
  chatId: string;
  message: ChatMessage;
  prevMessage?: ChatMessage;
}) {
  const { id, content, role } = message;

  return (
    <div className="flex flex-row items-center w-full px-2 py-4 overflow-x-hidden bg-white border border-t-slate-300">
      <div className="flex flex-col content-start">
        {role === "user" ? (
          <Avatar size="md" className="border shadow-lg" />
        ) : (
          <TbCross
            className={`${squareDimensionClasses["md"]} p-2 text-md text-center border rounded-full shadow-lg`}
          />
        )}
      </div>
      <div className="flex flex-col w-full pl-5 pr-3 overflow-x-clip">
        <div className="w-full break-words whitespace-pre-wrap">{content}</div>
        {role !== "user" && (
          <ResponseSources aiResponseId={id} chatId={chatId} />
        )}
      </div>
    </div>
  );
}
