// packages/website/src/lib/components/chat/message/ResponseSources.svelte
<script lang="ts">
  import { PUBLIC_API_URL } from '$env/static/public';
  import * as Accordion from '$lib/components/ui/accordion';
  import { Spinner } from '$lib/components/ui/spinner';
  import { session } from '$lib/stores/user';
  import { graphql } from '@revelationsai/client/graphql';
  import type { SourceDocument } from '@revelationsai/core/model/source-document';
  import { createQuery } from '@tanstack/svelte-query';
  import graphqlRequest from 'graphql-request';
  import { derived, writable } from 'svelte/store';

  let argAiResponseId: string;
  export { argAiResponseId as aiResponseId };

  const aiResponseId = writable(argAiResponseId);
  $: aiResponseId.set(argAiResponseId);

  let argIsChatLoading = false;
  export { argIsChatLoading as isChatLoading };
  const isChatLoading = writable(argIsChatLoading);
  $: isChatLoading.set(argIsChatLoading);

  let sourceDocs = writable<Pick<SourceDocument, 'id' | 'metadata'>[]>([]);

  const graphqlQuery = graphql(`
    query GetAiResponseSourceDocuments($aiResponseId: String!) {
      aiResponse(id: $aiResponseId) {
        id
        sourceDocuments {
          id
          metadata
        }
      }
    }
  `);

  const query = createQuery(
    derived([session, aiResponseId], ([$session, $aiResponseId]) => ({
      queryKey: [
        'ai-response-source-documents',
        { aiResponseId: $aiResponseId, session: $session }
      ],
      queryFn: async () => {
        return await graphqlRequest(
          `${PUBLIC_API_URL}/graphql`,
          graphqlQuery,
          {
            aiResponseId: $aiResponseId
          },
          {
            authorization: `Bearer ${$session}`
          }
        );
      }
    }))
  );
  query.subscribe(({ data }) => {
    if (data?.aiResponse?.sourceDocuments) {
      sourceDocs.set(
        data.aiResponse.sourceDocuments
          .map((doc) => ({
            id: doc.id,
            metadata: JSON.parse(doc.metadata)
          }))
          .filter(
            (doc, index, arr) => arr.findIndex((d) => d.metadata.url === doc.metadata.url) === index
          )
      );
    }
  });

  $: isLoading = $isChatLoading || $query.isLoading;
</script>

<Accordion.Root class="border-foreground w-full rounded-xl border border-opacity-15 px-3 py-1">
  <Accordion.Item value="sources" class="border-b-0">
    <Accordion.Trigger
      class="text-foreground flex w-full place-items-center text-sm"
      disabled={isLoading}
    >
      <div class="flex place-items-center justify-start">
        All Sources
        {#if isLoading}
          <Spinner size="sm" class="ml-2" variant="foreground" />
        {:else}
          ({$sourceDocs.length})
        {/if}
      </div>
    </Accordion.Trigger>
    <Accordion.Content>
      {#if $sourceDocs.length > 0}
        <ol class="flex w-full list-outside list-decimal flex-col space-y-1">
          {#each $sourceDocs as sourceDoc (sourceDoc.id)}
            <li class={`list-item truncate text-xs text-gray-400`}>
              <a
                href={sourceDoc.metadata.url ?? '#'}
                target="_blank"
                rel="noopener noreferrer"
                class="hover:underline"
              >
                <span>{sourceDoc.metadata.title ?? sourceDoc.metadata.name}</span>
                {#if sourceDoc.metadata.author}
                  <span class="ml-1 text-slate-500">by {sourceDoc.metadata.author}</span>
                {/if}
              </a>
            </li>
          {/each}
        </ol>
      {:else}
        <ul class="flex w-full flex-col space-y-1">
          <li class={`truncate text-xs text-gray-400`}>None</li>
        </ul>
      {/if}
    </Accordion.Content>
  </Accordion.Item>
</Accordion.Root>

// packages/web/src/components/chat/ResponseSources.tsx
"use client";

import { SolidLineSpinner } from "@components/loading";
import { apiConfig } from "@configs/index";
import { useSession } from "@hooks/session";
import { Query } from "@revelationsai/core/database/helpers";
import { SourceDocument } from "@revelationsai/core/database/model";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { IoIosArrowForward } from "react-icons/io";

export function ResponseSources({
  aiResponseId,
  chatId,
}: {
  aiResponseId: string;
  chatId: string;
}) {
  const { session } = useSession();
  const [showSources, setShowSources] = useState(false);
  const [sources, setSources] = useState<SourceDocument[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [hasFetchedSources, setHasFetchedSources] = useState(false);

  const getSources = useCallback(async () => {
    if (hasFetchedSources) return;
    try {
      setIsLoading(true);
      let query: Query = {
        AND: [],
      };
      if (aiResponseId) {
        query.AND!.push({
          eq: {
            column: "aiId",
            value: aiResponseId,
          },
        });
      }
      if (chatId) {
        query.AND!.push({
          eq: {
            column: "chatId",
            value: chatId,
          },
        });
      }
      const fetchAiResponsesResponse = await fetch(
        `${apiConfig.url}/ai-responses/search`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${session}`,
          },
          body: JSON.stringify({
            query,
          } satisfies {
            query: Query;
          }),
        }
      );
      const { entities: aiResponses } = await fetchAiResponsesResponse.json();
      const aiResponse = aiResponses[0];

      const response = await fetch(
        `${apiConfig.url}/ai-responses/${aiResponse.id}/source-documents`,
        {
          method: "GET",
          headers: {
            Authorization: `Bearer ${session}`,
          },
        }
      );
      const foundSourceDocuments: SourceDocument[] = await response.json();
      setSources(
        foundSourceDocuments.filter((sourceDoc, index) => {
          const firstIndex = foundSourceDocuments.findIndex(
            (otherSourceDoc) =>
              (sourceDoc.metadata as any).name ===
              (otherSourceDoc.metadata as any).name
          );
          return firstIndex === index;
        })
      );
      setHasFetchedSources(true);
    } catch (error) {
      console.error(error);
    }
    setIsLoading(false);
  }, [hasFetchedSources, aiResponseId, chatId]);

  useEffect(() => {
    if (showSources) {
      getSources();
    }
  }, [showSources, getSources]);

  return (
    <div className="flex flex-col w-full overflow-x-hidden grow-0">
      <div
        className="flex flex-row items-center w-full mt-2 space-x-1 cursor-pointer"
        onClick={() => {
          setShowSources(!showSources);
        }}
      >
        <div className="text-sm text-blue-400">Sources</div>
        <IoIosArrowForward
          className={`text-sm duration-300 ${
            showSources ? "rotate-90" : "rotate-0"
          }`}
        />
      </div>
      {isLoading && <SolidLineSpinner size="sm" colorscheme={"dark"} />}
      {sources && (
        <ul
          className={`flex flex-col w-full space-y-1 duration-300 ${
            showSources ? "" : "hidden"
          }`}
        >
          {sources.map((sourceDoc) => (
            <li key={sourceDoc.id} className={`text-xs text-gray-400 truncate`}>
              <Link
                href={(sourceDoc.metadata as any).url ?? "#"}
                target="_blank"
                rel="noopener noreferrer"
                className="hover:underline"
              >
                {(sourceDoc.metadata as any).name}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
