// packages/website/src/lib/components/chat/Sidebar.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { createChat, deleteChat, getChats, updateChat } from '$lib/services/chat';
	import type { Chat } from '@core/model';
	import Icon from '@iconify/svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import Moment from 'moment';

	export let initChats: Chat[] = [];
	export let activeChatId: string | undefined = undefined;

	let isOpen = false;
	let limit = 5;
	let chats: Chat[] = [];
	let isLoadingInitial = false;
	let isLoadingMore = false;
	let loadingChatId: string | undefined = undefined;
	let editChatId: string | undefined = undefined;
	let editIsLoading = false;

	const handleCreate = async () => {
		await createChat(
			{
				name: 'New Chat'
			},
			{
				session: $page.data.session
			}
		);
		if (chats.length >= limit) {
			limit++;
		}
		$query.refetch();
	};

	const handleEdit = async (
		event: SubmitEvent & { currentTarget: EventTarget & HTMLFormElement },
		id: string
	) => {
		const formData = new FormData(event.currentTarget);
		const name = formData.get('name') as string;
		if (!name) {
			return;
		}
		editIsLoading = true;
		updateChat(
			id,
			{
				name: name
			},
			{
				session: $page.data.session
			}
		).finally(async () => {
			await $query.refetch();
			editIsLoading = false;
			editChatId = undefined;
		});
	};

	const handleDelete = async (id: string) => {
		if (confirm('Are you sure you want to delete this chat?')) {
			await deleteChat(id, { session: $page.data.session });
			if (activeChatId === id) {
				goto('/chat');
			} else {
				$query.refetch();
			}
		}
	};

	$: query = createQuery({
		queryKey: ['chats'],
		queryFn: () => getChats({ limit, session: $page.data.session }).then((r) => r.chats),
		initialData: initChats
	});

	$: query?.subscribe(({ data, isLoading, isFetching }) => {
		chats = data ?? [];

		if ((isLoading || isFetching) && chats.length === 0) {
			isLoadingInitial = true;
		} else {
			isLoadingInitial = false;
		}

		if ((isLoading || isFetching) && limit > chats.length) {
			isLoadingMore = true;
		} else {
			isLoadingMore = false;
		}
	});

	$: if ($page.url.pathname) {
		isOpen = false;
		loadingChatId = undefined;
	}
</script>

<div
	class={`absolute flex h-full max-h-full bg-slate-700 border-t-2 duration-300 z-30 lg:w-2/5 lg:static ${
		isOpen ? 'w-full' : 'w-0'
	}`}
>
	<div class="relative flex flex-col w-full h-full">
		<button
			class={`absolute top-2 p-1 z-40 rounded-full bg-white border border-slate-700 cursor-pointer duration-300 lg:hidden ${
				isOpen ? 'rotate-0 right-2' : 'rotate-180 -right-10 opacity-75'
			}`}
			on:click|preventDefault={() => (isOpen = !isOpen)}
		>
			<Icon icon="formkit:arrowleft" height={20} width={20} />
		</button>
		<div
			class={`h-full w-full overflow-y-scroll py-4 px-6 text-white lg:px-2 lg:visible ${
				isOpen ? 'visible' : 'invisible'
			}`}
		>
			<h1 class="px-2 mb-3 text-2xl font-medium">Chat History</h1>
			<div class="flex flex-col content-center w-full space-y-2">
				<div class="flex justify-center w-full">
					<button
						class="flex items-center justify-center w-full py-2 my-2 border rounded-lg hover:bg-slate-900"
						on:click|preventDefault={() => handleCreate()}
					>
						New chat
						<Icon icon="ic:baseline-plus" class="text-xl" />
					</button>
				</div>
				{#if isLoadingInitial}
					<div class="flex justify-center w-full">
						<div class="flex items-center justify-center py-5">
							<span class="loading loading-spinner loading-lg" />
						</div>
					</div>
				{/if}
				{#if $query.isSuccess}
					{#each chats as chat (chat.id)}
						<div
							class={`flex w-full place-items-center justify-between px-4 py-2 rounded-lg hover:bg-slate-900 active:bg-slate-900 ${
								activeChatId === chat.id ? 'bg-slate-800' : ''
							}`}
						>
							<a
								href={`/chat/${chat.id}`}
								class="flex flex-col w-5/6"
								on:click={() => {
									if (activeChatId === chat.id) {
										isOpen = false;
										return;
									}
									loadingChatId = chat.id;
								}}
							>
								{#if editChatId === chat.id}
									{#if editIsLoading}
										<div class="flex w-full mb-1">
											<span class="loading loading-spinner loading-sm" />
										</div>
									{:else}
										<form
											on:submit|preventDefault={(event) => handleEdit(event, chat.id)}
											class="flex flex-col w-full"
										>
											<input
												name="name"
												class="w-full py-1 bg-transparent rounded-lg focus:ring-0 focus:border-none focus:outline-none"
												autocomplete="off"
												autofocus
												on:focusout={() => (editChatId = undefined)}
											/>
										</form>
									{/if}
								{:else}
									<div class="text-white truncate">{chat.name}</div>
								{/if}
								<div class="text-sm text-gray-400 truncate">
									{Moment(chat.createdAt).format('M/D/YYYY h:mma')}
								</div>
							</a>
							<div class="flex justify-center space-x-1 place-items-center">
								{#if loadingChatId === chat.id}
									<div class="mr-2">
										<span class="loading loading-spinner loading-xs" />
									</div>
								{:else}
									<button
										class="flex w-full h-full"
										on:click={() => {
											if (editChatId === chat.id) {
												editChatId = undefined;
												return;
											}
											editChatId = chat.id;
										}}
									>
										<Icon
											icon={editChatId === chat.id && !editIsLoading
												? 'mdi:cancel'
												: 'tdesign:edit'}
											width={20}
											height={20}
											class="hover:text-yellow-400 active:text-yellow-400"
										/>
									</button>
									<button
										class="flex w-full h-full"
										on:click|preventDefault={() => handleDelete(chat.id)}
									>
										<Icon
											icon="mdi:trash-outline"
											width={20}
											height={20}
											class="hover:text-red-500 active:text-red-500"
										/>
									</button>
								{/if}
							</div>
						</div>
					{/each}
					{#if !isLoadingMore && chats.length >= limit}
						<button
							class="flex justify-center py-2 text-center border border-white rounded-lg hover:bg-slate-900"
							on:click|preventDefault={() => (limit = limit + 5)}
						>
							View more
						</button>
					{:else if isLoadingMore}
						<div class="flex justify-center w-full">
							<div class="flex items-center justify-center py-5">
								<span class="loading loading-spinner loading-md" />
							</div>
						</div>
					{/if}
				{:else if $query.isError}
					<div>
						Error fetching devotions: {$query.error}
					</div>
				{/if}
			</div>
		</div>
	</div>
</div>

// packages/web/src/components/chat/Sidebar.tsx
"use client";

import { apiConfig } from "@configs/index";
import { Chat } from "@core/model";
import { useSession } from "@hooks/session";
import Moment from "moment";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  Dispatch,
  SetStateAction,
  useCallback,
  useEffect,
  useState,
} from "react";
import { AiOutlineDelete } from "react-icons/ai";
import { BsArrowLeftShort, BsPlus } from "react-icons/bs";
import { KeyedMutator } from "swr";
import { SolidLineSpinner } from "..";

type SidebarProps = {
  activeChatId?: string;
  isOpen: boolean;
  setIsOpen: Dispatch<SetStateAction<boolean>>;
  chats: Chat[];
  mutate: KeyedMutator<Chat[]>;
  isLoading: boolean;
  limit: number;
  setLimit: Dispatch<SetStateAction<number>>;
};

export function Sidebar({
  activeChatId,
  isOpen,
  setIsOpen,
  chats,
  mutate,
  isLoading,
  limit,
  setLimit,
}: SidebarProps) {
  const router = useRouter();
  const { session } = useSession();
  const [isLoadingInitial, setIsLoadingInitial] = useState(true);
  const [isLoadingMore, setIsLoadingMore] = useState(false);

  const createChat = useCallback(async () => {
    const response = await fetch(`${apiConfig.url}/chats`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${session}`,
      },
      body: JSON.stringify({
        name: "New Chat",
      }),
    });
    const chat = await response.json();
    if (chats.length >= limit) {
      setLimit((prevLimit) => prevLimit + 1);
    }
    mutate([chat, ...chats]);
  }, [chats, limit, mutate, session, setLimit]);

  const deleteChat = useCallback(
    (id: string) => {
      if (confirm("Are you sure you want to delete this chat?")) {
        fetch(`${apiConfig.url}/chats/${id}`, {
          method: "DELETE",
          headers: {
            Authorization: `Bearer ${session}`,
          },
        });
        setTimeout(() => {
          mutate(chats!.filter((chat) => chat.id !== id));
          if (activeChatId === id) {
            router.push("/chat");
          }
        }, 1000);
      }
    },
    [activeChatId, chats, mutate, router, session]
  );

  const handleGetMoreChats = () => {
    setLimit((prevLimit) => prevLimit + 5);
    mutate(chats);
  };

  useEffect(() => {
    if (chats.length === 0 && isLoading) {
      setIsLoadingInitial(true);
    } else {
      setIsLoadingInitial(false);
    }
  }, [chats, isLoading]);

  useEffect(() => {
    if (chats.length <= limit && isLoading) {
      setIsLoadingMore(true);
    } else {
      setIsLoadingMore(false);
    }
  }, [chats, isLoading, limit]);

  return (
    <div
      className={`absolute flex h-full max-h-full bg-slate-700 border-t-2 duration-300 z-30 lg:w-1/4 lg:static ${
        isOpen ? "w-full" : "w-0"
      }`}
    >
      <div className="relative flex flex-col w-full h-full">
        <div
          className={`absolute top-2 p-1 z-40 rounded-full bg-white border border-slate-700 cursor-pointer duration-300 lg:hidden ${
            isOpen ? "rotate-0 right-2" : "rotate-180 -right-10 opacity-75"
          }`}
          onClick={() => setIsOpen(!isOpen)}
        >
          <BsArrowLeftShort className="text-xl text-slate-700" />
        </div>
        <div
          className={`h-full w-full overflow-y-scroll py-4 px-3 text-white lg:px-6 lg:visible ${
            isOpen ? "visible" : "invisible"
          }`}
        >
          <h1 className="px-2 text-2xl font-bold">Chat History</h1>
          <div className="flex flex-col content-center w-full space-y-2">
            <div className="flex justify-center w-full">
              <button
                className="flex items-center justify-center w-full py-2 my-2 border rounded-lg hover:bg-slate-900"
                onClick={() => createChat()}
              >
                New chat
                <BsPlus className="text-xl" />
              </button>
            </div>
            {isLoadingInitial && (
              <div className="flex justify-center w-full">
                <div className="flex items-center justify-center py-5">
                  <SolidLineSpinner size="lg" colorscheme={"light"} />
                </div>
              </div>
            )}
            {chats.map((chat) => (
              <div
                key={chat.id}
                className={`flex place-items-center p-2 rounded-lg hover:bg-slate-900 ${
                  activeChatId === chat.id ? "bg-slate-800" : ""
                }`}
              >
                <Link href={`/chat/${chat.id}`} className="flex flex-col w-5/6">
                  <div className="text-white truncate">{chat.name}</div>
                  <div className="text-sm text-gray-400 truncate">
                    {Moment(chat.createdAt).format("M/D/YYYY h:mma")}
                  </div>
                </Link>
                <div className="flex justify-center flex-1">
                  <AiOutlineDelete
                    className="text-lg cursor-pointer hover:text-red-500"
                    onClick={() => deleteChat(chat.id)}
                  />
                </div>
              </div>
            ))}
            {isLoadingMore && (
              <div className="flex justify-center w-full">
                <div className="flex items-center justify-center py-5">
                  <SolidLineSpinner size="md" colorscheme={"light"} />
                </div>
              </div>
            )}
            {chats.length >= limit && !isLoadingMore && (
              <button
                className="flex justify-center py-2 text-center border border-white rounded-lg hover:bg-slate-900"
                onClick={handleGetMoreChats}
              >
                View more
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
