// packages/web/src/components/chat/Message.tsx
"use client";

import { Avatar } from "@components/user";
import { TbCross } from "react-icons/tb";
import { ResponseSources } from "./ResponseSources";

export function Message({
  chatId,
  id,
  text,
  sender,
}: {
  chatId: string;
  id: string;
  text: string;
  sender: string;
}) {
  return (
    <div className="flex flex-row items-center w-full px-2 py-4 bg-white border border-t-slate-300">
      <div className="flex flex-col content-start">
        {sender === "user" ? (
          <Avatar size="md" className="border shadow-lg" />
        ) : (
          <div className="relative w-10 h-10 border rounded-full shadow-lg">
            <TbCross className="absolute text-xl top-[25%] left-[25%]" />
          </div>
        )}
      </div>
      <div className="flex flex-col pl-5 pr-3">
        <div className="break-words whitespace-pre-wrap">{text}</div>
        {sender !== "user" && (
          <ResponseSources aiResponseId={id} chatId={chatId} />
        )}
      </div>
    </div>
  );
}

// packages/website/src/lib/components/chat/message/Message.svelte
<script lang="ts">
  import type { RAIChatMessage } from '@revelationsai/core/model/chat/message';
  import type { ModelInfo } from '@revelationsai/core/model/llm';
  import type { User } from '@revelationsai/core/model/user';
  import Day from 'dayjs';
  import LogoIcon from '../../branding/LogoIcon.svelte';
  import AnonymousAvatar from '../../user/AnonymousAvatar.svelte';
  import Avatar from '../../user/Avatar.svelte';
  import CopyButton from './CopyButton.svelte';
  import MessageMarkdown from './MessageMarkdown.svelte';
  import ResponseSources from './ResponseSources.svelte';
  import ShareMessageButton from './ShareMessageButton.svelte';

  export let user: User | undefined = undefined;
  export let message: RAIChatMessage;
  export let prevMessage: RAIChatMessage | undefined = undefined;
  export let isChatLoading = false;
  export let isLastMessage = false;
  export let modelInfos: { [k: string]: ModelInfo };

  let includePreviousMessage: boolean = false;
  let sharableContent: string = message.content;

  let id: string;
  let uuid: string | undefined;
  let role: RAIChatMessage['role'];
  let content: string;

  $: ({ id, uuid, role, content } = message);

  $: if (includePreviousMessage && prevMessage) {
    const { role: prevRole, content: prevContent } = prevMessage;
    sharableContent = `${prevRole === 'user' ? 'Me' : 'RevelationsAI'}: ${prevContent}\n\n${
      role === 'user' ? 'Me' : 'RevelationsAI'
    }: ${content}`;
  } else {
    sharableContent = `${role === 'user' ? 'Me' : 'RevelationsAI'}: ${content}`;
  }
</script>

<div class="border-t-foreground relative flex w-full flex-row border px-2 py-5">
  {#if message.modelId}
    <div
      class="bg-background border-foreground absolute -top-4 left-1 mt-2 flex-shrink-0 rounded-xl border text-xs"
    >
      <span class="px-2 py-1">
        {modelInfos[message.modelId]?.name ?? message.modelId}
      </span>
    </div>
  {/if}
  <div class="flex w-12 flex-col content-start">
    {#if role === 'user'}
      <Avatar {user} size="lg" class="border border-slate-100 shadow-xl" />
    {:else if role === 'anonymous'}
      <AnonymousAvatar size="sm" class="border border-slate-100 shadow-xl" />
    {:else}
      <LogoIcon size="sm" class="w-12 rounded-full shadow-xl" />
    {/if}
  </div>
  <div class="flex w-full flex-col overflow-x-clip px-3">
    <MessageMarkdown {content} />
    <div
      class={`flex w-full ${role !== 'user' && !(isLastMessage && isChatLoading) ? 'justify-between' : 'justify-end'}`}
    >
      {#if role !== 'user' && !(isLastMessage && isChatLoading)}
        <div class="mr-2 flex w-2/3 lg:w-3/4">
          <ResponseSources aiResponseId={uuid ?? id} {isChatLoading} />
        </div>
      {/if}
      <div class="mt-1 flex w-1/3 flex-col place-items-end justify-start lg:w-1/4">
        <div class="flex place-items-end justify-end space-x-2">
          <div class="mt-2 flex-shrink-0 text-xs text-gray-400">
            {Day(message.createdAt).format('M/D/YY h:mm a')}
          </div>
        </div>
        <div class="mt-1 flex place-items-start justify-end">
          {#if role !== 'user' && !(isLastMessage && isChatLoading)}
            <div class="flex">
              <ShareMessageButton />
              <CopyButton content={sharableContent} />
            </div>
          {:else}
            <CopyButton content={sharableContent} />
          {/if}
        </div>
      </div>
    </div>
  </div>
</div>
