// packages/website/src/lib/components/chat/Message.svelte
<script lang="ts">
	import type { UserWithRoles } from '@core/model';
	import type { Message } from 'ai';
	import Cross from '../branding/Cross.svelte';
	import Avatar from '../user/Avatar.svelte';
	import ResponseSources from './ResponseSources.svelte';

	export let chatId: string | undefined;
	export let message: Message;
	export let prevMessage: Message | undefined;
	export let user: UserWithRoles;

	const { id, content, role } = message;
</script>

<div
	class="flex flex-row items-center w-full px-2 py-4 overflow-x-hidden bg-white border border-t-slate-300"
>
	<div class="flex flex-col content-start">
		{#if role === 'user'}
			<Avatar {user} size="md" class="border shadow-lg" />
		{:else}
			<Cross />
		{/if}
	</div>
	<div class="flex flex-col w-full pl-5 pr-3 overflow-x-clip">
		<div class="w-full break-words whitespace-pre-wrap">{content}</div>
		{#if role !== 'user'}
			<ResponseSources aiResponseId={id} {chatId} />
		{/if}
	</div>
</div>

// packages/frontend/components/chat/Message.tsx
import { TbCross } from "react-icons/tb";

type MessageProps = {
  text: string;
  sender: string;
};

export function Message({ text, sender }: MessageProps) {
  return (
    <div className="inline-flex w-full items-center px-2 py-4 bg-white border border-t-slate-300">
      <div className="p-2 rounded-full bg-slate-700 text-white">
        {sender === "user" ? (
          <div className="text-sm">You</div>
        ) : (
          <TbCross className="text-lg" />
        )}
      </div>
      <div className="pl-5 pr-3 break-words whitespace-pre-wrap">{text}</div>
    </div>
  );
}
