// apps/website/src/lib/components/bible/chat/button.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { useBibleStore } from '$lib/runes/bible.svelte';
  import { MessageSquare } from 'lucide-svelte';

  const { chatOpen, setChatOpen } = useBibleStore();
</script>

<Button
  class={`mx-auto h-12 w-20 rounded-t-2xl transition duration-200 ${chatOpen ? 'translate-y-full' : 'delay-200'}`}
  onclick={() => setChatOpen(!chatOpen)}
>
  <MessageSquare size={20} />
</Button>

// apps/website/src/lib/components/bible/chat/button.tsx
import { Button } from '@/components/ui/button';
import { useBibleStore } from '@/hooks/use-bible-store';
import { MessageSquare } from 'lucide-react';

export default function ChatButton() {
  const { chatOpen, setChatOpen } = useBibleStore((store) => ({
    chatOpen: store.chatOpen,
    setChatOpen: store.setChatOpen
  }));

  return (
    <Button
      className={`mx-auto h-12 w-20 rounded-t-2xl transition duration-200 ${chatOpen ? 'translate-y-full' : 'delay-200'}`}
      onClick={() => setChatOpen(!chatOpen)}
    >
      <MessageSquare size={20} />
    </Button>
  );
}
