// apps/www/src/routes/(with-sidebar)/admin.tsx
import { AdminSidebar } from '@/www/components/admin/sidebar';
import { SidebarProvider, SidebarTrigger } from '@/www/components/ui/sidebar';
import { useProtectAdmin } from '@/www/hooks/use-protect';
import { useWindowSize } from '@solid-primitives/resize-observer';
import { type JSX, createMemo } from 'solid-js';

export default function AdminLayout(props: { children: JSX.Element }) {
  useProtectAdmin('/');

  const windowSize = useWindowSize();
  const isMobile = createMemo(() => windowSize.width < 768);

  return (
    <SidebarProvider
      class='min-h-full flex-1 overflow-hidden'
      style={{
        '--sidebar-width': '20rem',
      }}
      defaultOpen={!isMobile()}
    >
      <AdminSidebar />
      <div class='flex h-full w-full flex-1 p-5'>
        <SidebarTrigger />
        <div class='mx-auto flex h-full w-full flex-col'>{props.children}</div>
      </div>
    </SidebarProvider>
  );
}

// apps/www/app/routes/_with-sidebar/admin.tsx
import { AdminSidebar } from '@/www/components/admin/sidebar';
import { SidebarProvider, SidebarTrigger } from '@/www/components/ui/sidebar';
import { Outlet, createFileRoute, redirect } from '@tanstack/react-router';
import { useMemo } from 'react';
import { useWindowSize } from 'usehooks-ts';

export const Route = createFileRoute('/_with-sidebar/admin')({
  beforeLoad: ({ context, location }) => {
    if (!context.user) {
      throw redirect({ to: '/sign-in', search: { redirectUrl: location.href } });
    }

    if (!context.roles?.some((role) => role.id === 'admin')) {
      throw redirect({ to: '/' });
    }
  },
  component: RouteComponent,
});

function RouteComponent() {
  const windowSize = useWindowSize();
  const isMobile = useMemo(() => windowSize.width < 768, [windowSize]);

  return (
    <SidebarProvider
      className='min-h-full flex-1 overflow-hidden'
      style={
        {
          '--sidebar-width': '20rem',
        } as React.CSSProperties
      }
      defaultOpen={!isMobile}
    >
      <AdminSidebar />
      <div className='flex h-full w-full flex-1 p-5'>
        <SidebarTrigger />
        <div className='mx-auto flex h-full w-full flex-col'>
          <Outlet />
        </div>
      </div>
    </SidebarProvider>
  );
}
