// apps/www/app/components/chat/sidebar/index.tsx
import { db } from '@/core/database';
import { chats as chatsTable, messages as messagesTable } from '@/core/database/schema';
import { ilike } from '@/core/database/utils';
import { cn } from '@/www/lib/utils';
import { requireAuthMiddleware } from '@/www/server/middleware/auth';
import { getHighlightedContent } from '@/www/utils/get-highlighted-content';
import { useInfiniteQuery } from '@tanstack/react-query';
import { useNavigate } from '@tanstack/react-router';
import { useLocation } from '@tanstack/react-router';
import { createServerFn } from '@tanstack/react-start';
import { formatDate } from 'date-fns';
import { type SQL, and, desc, eq, getTableColumns } from 'drizzle-orm';
import { Menu, PenBox, Search, X } from 'lucide-react';
import { useState } from 'react';
import { z } from 'zod';
import { useChatStore } from '../../../contexts/chat';
import { LogoSmall } from '../../branding/logo-small';
import { NavigationDropdown } from '../../navigation/dropdown';
import { QueryBoundary } from '../../query-boundary';
import { Button } from '../../ui/button';
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarInput,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from '../../ui/sidebar';
import { Tooltip, TooltipContent, TooltipTrigger } from '../../ui/tooltip';
import { H3, H6 } from '../../ui/typography';
import { DeleteChatButton } from './delete-chat-button';

// @ts-ignore
const getChats = createServerFn({ method: 'GET' })
  .middleware([requireAuthMiddleware])
  .validator(
    z.object({ offset: z.number(), limit: z.number(), searchQuery: z.string().optional() }),
  )
  .handler(async ({ context, data }) => {
    let chatCondition: SQL | undefined = eq(chatsTable.userId, context.user.id);
    if (data.searchQuery) {
      chatCondition = and(chatCondition, ilike(chatsTable.name, `%${data.searchQuery}%`));
    }
    const query = db
      .select({
        ...getTableColumns(chatsTable),
        ...(data.searchQuery ? { message: getTableColumns(messagesTable) } : {}),
      })
      .from(chatsTable)
      .where(chatCondition);
    if (data.searchQuery) {
      query.leftJoin(
        messagesTable,
        and(
          eq(chatsTable.id, messagesTable.chatId),
          ilike(messagesTable.content, `%${data.searchQuery}%`),
        ),
      );
    }
    query.orderBy(desc(chatsTable.updatedAt)).limit(data.limit).offset(data.offset);

    const chats = await query.execute();

    return {
      chats,
      nextCursor: chats.length === data.limit ? data.offset + chats.length : null,
    };
  });

export const getChatsQueryOptions = (searchQuery?: string) => ({
  queryKey: ['chats', { searchQuery }],
  queryFn: ({ pageParam }: { pageParam: number }) =>
    getChats({ data: { offset: pageParam, limit: 15, searchQuery } }),
  initialPageParam: 0,
  // @ts-ignore
  getNextPageParam: (lastPage: Awaited<ReturnType<typeof getChats>>) => lastPage.nextCursor,
});

export const ChatSidebar = () => {
  const navigate = useNavigate();

  const chatStore = useChatStore();
  const { isMobile, toggleSidebar } = useSidebar();

  const [searchQuery, setSearchQuery] = useState('');
  const chatsQuery = useInfiniteQuery({
    ...getChatsQueryOptions(searchQuery),
    placeholderData: (prev) => prev,
  });

  const isChatPage = useLocation({
    select: (location) => location.pathname.startsWith('/chat'),
  });

  return (
    <Sidebar
      className='h-full pt-safe-offset-2 pr-1 pb-safe-offset-2 pl-safe-offset-2'
      gapFixerClassName='h-full'
      variant={isChatPage ? 'sidebar' : 'sheet'}
    >
      <SidebarHeader className='flex flex-col gap-2'>
        <div className='flex items-center justify-between'>
          <H3>Chat History</H3>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                size='icon'
                variant='ghost'
                onClick={() => {
                  chatStore.setChatId(null);
                  if (!isChatPage || isMobile) {
                    toggleSidebar();
                  }
                }}
                aria-label='Start new chat'
              >
                <PenBox />
              </Button>
            </TooltipTrigger>
            <TooltipContent>New Chat</TooltipContent>
          </Tooltip>
        </div>
        <div className='relative'>
          <Search className='-translate-y-1/2 absolute top-1/2 left-3 size-4 text-muted-foreground' />
          <SidebarInput
            type='text'
            placeholder='Search chats'
            value={searchQuery}
            onInput={(e) => setSearchQuery(e.currentTarget.value)}
            className='pr-8 pl-9'
          />
          {searchQuery && (
            <Button
              variant='ghost'
              size='icon'
              className='-translate-y-1/2 absolute top-1/2 right-1 size-6 p-0.5'
              onClick={() => setSearchQuery('')}
            >
              <X className='size-4' />
            </Button>
          )}
        </div>
      </SidebarHeader>
      <SidebarContent>
        <QueryBoundary query={chatsQuery}>
          {(data) => {
            const chats = data.pages.flatMap((page) => page.chats);
            return (
              <SidebarMenu className='pr-2'>
                {chats.length === 0 ? (
                  <div className='flex h-full w-full flex-1 items-center justify-center px-5 py-10'>
                    <H6>No chats found</H6>
                  </div>
                ) : (
                  chats.map((chat, idx) => (
                    <SidebarMenuItem
                      key={chat.id}
                      data-index={idx}
                      className={cn(
                        'group/chat-item flex h-fit w-full items-center justify-between overflow-hidden rounded-lg px-1 hover:bg-accent',
                        chatStore.chat?.id === chat.id && 'bg-muted',
                      )}
                    >
                      <SidebarMenuButton
                        onClick={() => {
                          chatStore.setChatId(chat.id);
                          if (isChatPage) {
                            navigate({ to: `/chat/${chat.id}` });
                          }
                          if (!isChatPage || isMobile) {
                            toggleSidebar();
                          }
                        }}
                        className='flex min-h-fit w-full flex-1 grow p-3 text-left'
                      >
                        <div className='flex w-full flex-col'>
                          <div className='truncate'>
                            {getHighlightedContent(chat.name, searchQuery)}
                          </div>
                          <div className='text-muted-foreground text-xs'>
                            {formatDate(chat.updatedAt, 'MMMM d, yyyy')}
                          </div>
                          {chat.message?.content && (
                            <div className='mt-1 text-xs'>
                              {getHighlightedContent(chat.message.content, searchQuery, 50)}
                            </div>
                          )}
                        </div>
                      </SidebarMenuButton>
                      <DeleteChatButton chat={chat} />
                    </SidebarMenuItem>
                  ))
                )}
                {chatsQuery.hasNextPage && (
                  <Button
                    className='w-full'
                    disabled={chatsQuery.isFetchingNextPage}
                    onClick={() => chatsQuery.fetchNextPage()}
                  >
                    Load More
                  </Button>
                )}
              </SidebarMenu>
            );
          }}
        </QueryBoundary>
      </SidebarContent>
      <SidebarFooter>
        {isChatPage && (
          <NavigationDropdown
            variant='ghost'
            className='flex h-fit w-full items-center justify-between px-4 py-1'
          >
            <LogoSmall
              width={128}
              height={64}
              className='h-auto w-24'
              lightClassName='dark:hidden'
            />
            <Menu />
          </NavigationDropdown>
        )}
      </SidebarFooter>
    </Sidebar>
  );
};

// apps/web/src/components/chat/sidebar/index.tsx
import { useLocation, useNavigate } from '@solidjs/router';
import { createInfiniteQuery } from '@tanstack/solid-query';
import { db } from '@theaistudybible/core/database';
import { auth } from 'clerk-solidjs/server';
import day from 'dayjs';
import { Clock } from 'lucide-solid';
import { For, Match, Switch, createEffect, on } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';
import { cn } from '~/lib/utils';
import { useChatStore } from '../../providers/chat';
import { QueryBoundary } from '../../query-boundary';
import { Button, buttonVariants } from '../../ui/button';
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger
} from '../../ui/sheet';
import { Spinner } from '../../ui/spinner';
import { Tooltip, TooltipContent, TooltipTrigger } from '../../ui/tooltip';
import { H6 } from '../../ui/typography';
import { DeleteChatButton } from './delete-chat-button';
import { EditChatButton } from './edit-chat-button';

const getChats = async ({ offset, limit }: { offset: number; limit: number }) => {
  'use server';
  const { userId } = auth();
  if (!userId) {
    throw new Error('User is not authenticated');
  }

  const chats = await db.query.chats.findMany({
    where: (chats, { eq }) => eq(chats.userId, userId),
    orderBy: (chats, { desc }) => desc(chats.updatedAt),
    offset,
    limit
  });

  return {
    chats,
    nextCursor: chats.length === limit ? offset + chats.length : undefined
  };
};

export const ChatSidebar = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const [chatStore, setChatStore] = useChatStore();

  const chatsQuery = createInfiniteQuery(() => ({
    queryKey: ['chats', { limit: 10 }],
    queryFn: ({ pageParam }) => getChats({ offset: pageParam, limit: 10 }),
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage.nextCursor
  }));

  const [chats, setChats] = createStore(chatsQuery.data?.pages.flatMap((page) => page.chats) ?? []);
  createEffect(
    on(
      () => chatsQuery.data,
      (data) => {
        setChats(
          reconcile(data?.pages.flatMap((page) => page.chats) ?? [], {
            merge: true
          })
        );
      }
    )
  );

  return (
    <Sheet>
      <Tooltip>
        <TooltipTrigger
          as={SheetTrigger}
          class={cn(buttonVariants({ variant: 'ghost', size: 'icon' }))}
        >
          <Clock size={24} />
        </TooltipTrigger>
        <TooltipContent>View Chats</TooltipContent>
      </Tooltip>
      <SheetContent class="h-dvh" position="left">
        <div class="flex h-full w-full max-w-none flex-col space-y-2 px-2 pb-10">
          <SheetHeader>
            <SheetTitle>Chats</SheetTitle>
          </SheetHeader>
          <div class="flex max-h-full grow flex-col overflow-y-auto">
            <div class="flex grow flex-col gap-2 pr-3">
              <QueryBoundary query={chatsQuery}>
                {() => (
                  <For
                    each={chats}
                    fallback={
                      <div class="flex h-full w-full flex-1 items-center justify-center">
                        <H6>No chats yet</H6>
                      </div>
                    }
                  >
                    {(chat, idx) => (
                      <div
                        data-index={idx()}
                        class={cn(
                          'group flex h-fit w-full items-center justify-between gap-2 rounded-lg p-2 hover:bg-accent',
                          chatStore.chat?.id === chat.id && 'bg-muted'
                        )}
                      >
                        <SheetClose
                          as={Button}
                          variant="ghost"
                          onClick={() => {
                            setChatStore('chat', chat);
                            if (location.pathname.startsWith('/chat')) {
                              navigate(`/chat/${chat.id}`);
                            }
                          }}
                          class="flex h-fit flex-1 px-0 text-left"
                        >
                          <div class="flex flex-col">
                            <span class="line-clamp-2 group-hover:line-clamp-none">
                              {chat.name}
                            </span>
                            <span class="text-sm text-muted-foreground">
                              {day(chat.updatedAt).format('MMMM D, YYYY')}
                            </span>
                          </div>
                        </SheetClose>
                        <div class="invisible flex group-hover:visible">
                          <EditChatButton chat={chat} />
                          <DeleteChatButton chat={chat} />
                        </div>
                      </div>
                    )}
                  </For>
                )}
              </QueryBoundary>
              <Switch>
                <Match when={chatsQuery.isFetchingNextPage}>
                  <Spinner />
                </Match>
                <Match when={chatsQuery.hasNextPage}>
                  <Button
                    class="w-full"
                    onClick={() => {
                      if (!chatsQuery.isFetchingNextPage) {
                        chatsQuery.fetchNextPage();
                      }
                    }}
                  >
                    Load More
                  </Button>
                </Match>
              </Switch>
            </div>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
};
