// packages/auth-ui/src/lib/components/user/Avatar.svelte
<script lang="ts">
	import { user } from '$lib/stores/user';
	import { cn } from '@revelationsai/client/utils/class-names';
	import {
		squareDimensionClasses,
		textSizeClasses,
		type ComponentSize
	} from '@revelationsai/client/utils/sizing';

	export let size: ComponentSize = 'md';

	let className: string | undefined = undefined;
	export { className as class };

	$: ({ image, name, email } = $user!);
</script>

<div class="relative">
	<div
		class="absolute bottom-1 right-1 flex h-6 w-6 flex-col place-items-center justify-center rounded-full bg-blue-300 p-2 text-white"
	>
		<slot />
	</div>
	<div
		class={cn(
			`flex place-items-center justify-center overflow-hidden rounded-full bg-gray-300`,
			squareDimensionClasses[size],
			className
		)}
	>
		{#if image}
			<img
				class="h-full w-full rounded-full"
				src={image}
				width={192}
				height={192}
				alt="avatar"
				on:error={() => {
					image = null;
				}}
			/>
		{:else}
			<div class={cn('rounded-full uppercase text-white', textSizeClasses[size])}>
				{name ? name[0] : email ? email[0] : '?'}
			</div>
		{/if}
	</div>
</div>

// packages/web/src/components/user/Avatar.tsx
"use client";

import { useUser } from "@hooks/user";
import { ComponentSize, dimensionClasses } from "@lib/sizing";

export function Avatar({
  size = "md",
  largeSize = "md",
  className,
}: {
  size?: ComponentSize;
  largeSize?: ComponentSize;
  className?: string;
}) {
  const { user } = useUser();

  const dimensions = dimensionClasses[size];
  const largeDimensions = dimensionClasses[largeSize];

  if (user?.image) {
    return (
      <img
        className={`rounded-full ${dimensions} lg:${largeDimensions} ${
          className ?? ""
        }`}
        src={user.image}
        alt="avatar"
      />
    );
  }

  return (
    <div
      className={`relative rounded-full bg-gray-300 ${dimensions} lg:${largeDimensions} ${
        className ?? ""
      }`}
    >
      <div
        className={`absolute inset-0 flex items-center justify-center rounded-full text-white text-xl font-bold uppercase`}
      >
        {user?.name ? user.name[0] : user?.email ? user.email[0] : "?"}
      </div>
    </div>
  );
}
