// apps/www/app/components/chat/message/index.tsx
import { allChatModels } from '@/ai/models';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/www/components/ui/accordion';
import { Button } from '@/www/components/ui/button';
import { Markdown } from '@/www/components/ui/markdown';
import { cn } from '@/www/lib/utils';
import { getMessageId } from '@/www/utils/message';
import type { Message as AiMessage, useChat } from '@ai-sdk/react';
import { useCopyToClipboard } from '@uidotdev/usehooks';
import { Copy } from 'lucide-react';
import { Fragment, useMemo } from 'react';
import { toast } from 'sonner';
import { UserAvatar } from '../../auth/user-avatar';
import { Icon } from '../../branding/icon';
import { MessageReactionButtons } from './reaction-buttons';
import { Tool } from './tools';

export type MessageProps = {
  previousMessage?: AiMessage;
  nextMessage?: AiMessage;
  message: AiMessage;
  addToolResult: ReturnType<typeof useChat>['addToolResult'];
  isLoading: boolean;
};

export const Message = (props: MessageProps) => {
  const [, copy] = useCopyToClipboard();

  const modelInfo = useMemo(() => {
    const modelId =
      (props.message.annotations?.find(
        (a) =>
          typeof a === 'object' &&
          a !== null &&
          !Array.isArray(a) &&
          'modelId' in a &&
          typeof a.modelId === 'string',
      ) as { modelId: string } | undefined) ?? {};

    return allChatModels.find((m) => `${m.host}:${m.id}` === modelId);
  }, [props.message.annotations]);

  return (
    <article
      className={cn(
        'flex w-full max-w-3xl space-x-4 overflow-hidden px-3 py-4',
        props.previousMessage?.role === props.message.role ? 'border-t-0' : 'border-t',
      )}
      aria-label={`${props.message.role === 'assistant' ? 'AI' : 'User'} message`}
    >
      <div className='mt-2 flex h-full w-10 shrink-0 items-start'>
        {props.previousMessage?.role !== props.message.role &&
          (props.message.role === 'user' ? (
            <UserAvatar className='size-10 shrink-0' aria-label='User avatar' />
          ) : props.message.role === 'assistant' ? (
            <div
              className={cn(
                'relative flex size-10 shrink-0 place-items-center justify-center rounded-full bg-primary p-2',
                props.isLoading &&
                  !props.nextMessage &&
                  'before:absolute before:inset-0 before:scale-110 before:animate-spin before:rounded-full before:border-3 before:border-accent-foreground before:border-t-transparent before:border-r-transparent before:border-l-transparent before:duration-500',
              )}
              aria-label='AI assistant avatar'
            >
              <Icon width={300} height={300} className='shrink-0' aria-hidden='true' />
            </div>
          ) : null)}
      </div>
      <div className='flex w-full flex-col gap-4 overflow-hidden'>
        {(props.message.parts?.length ?? 0) === 0 ? (
          <>
            {(props.message.toolInvocations?.length ?? 0) > 0 &&
              props.message.toolInvocations &&
              props.message.toolInvocations.map((toolInvocation) => (
                <Tool
                  key={toolInvocation.toolCallId}
                  toolInvocation={toolInvocation}
                  addToolResult={props.addToolResult}
                  isLoading={props.isLoading && !props.nextMessage}
                />
              ))}
            {props.message.content && <Markdown>{props.message.content}</Markdown>}
          </>
        ) : (
          props.message.parts?.map((part, idx) => (
            <Fragment key={`${part.type}-${idx}`}>
              {part.type === 'text' && <Markdown>{part.text}</Markdown>}
              {part.type === 'reasoning' && (
                <Accordion type='single' collapsible>
                  <AccordionItem value='reasoning'>
                    <AccordionTrigger className='text-muted-foreground text-sm'>
                      View reasoning
                    </AccordionTrigger>
                    <AccordionContent>
                      <Markdown>{part.reasoning}</Markdown>
                    </AccordionContent>
                  </AccordionItem>
                </Accordion>
              )}
              {part.type === 'tool-invocation' && (
                <Tool
                  toolInvocation={part.toolInvocation}
                  addToolResult={props.addToolResult}
                  isLoading={props.isLoading && !props.nextMessage}
                />
              )}
            </Fragment>
          ))
        )}
        {props.message.role === 'assistant' && props.message.role !== props.nextMessage?.role && (
          <div className='flex items-center gap-1' role='toolbar' aria-label='Message actions'>
            {modelInfo && (
              <Button
                variant='outline'
                className='w-fit rounded-full border p-2 text-muted-foreground text-xs'
                asChild
              >
                <a href={modelInfo.link} target='_blank' rel='noopener noreferrer'>
                  {modelInfo.name}
                </a>
              </Button>
            )}
            <Button
              variant='ghost'
              className='h-fit w-fit p-1'
              onClick={() => {
                copy(props.message.content);
                toast.success('Text copied');
              }}
              aria-label='Copy message'
            >
              <Copy size={15} aria-hidden='true' />
            </Button>
            <MessageReactionButtons messageId={getMessageId(props.message)} />
          </div>
        )}
      </div>
    </article>
  );
};

// apps/web/src/components/chat/message.tsx
import { useChat } from '@ai-sdk/solid';
import { A } from '@solidjs/router';
import { allModels } from '@theaistudybible/ai/models';
import type { Message as AIMessage } from 'ai/solid';
import { Match, Show, Switch } from 'solid-js';
import { Markdown } from '~/components/ui/markdown';
import { useUser } from '~/hooks/clerk';
import { cn } from '~/lib/utils';
import Icon from '../branding/icon';
import { Tooltip, TooltipContent, TooltipTrigger } from '../ui/tooltip';
import { Tools } from './tools';

export type MessageProps = {
  previousMessage?: AIMessage;
  nextMessage?: AIMessage;
  message: AIMessage;
  addToolResult: ReturnType<typeof useChat>['addToolResult'];
};

export const Message = (props: MessageProps) => {
  const { user } = useUser();

  return (
    <div
      class={cn(
        'flex w-full space-x-4 py-2 pl-5',
        props.previousMessage?.role === props.message.role ? 'border-t-0' : 'border-t'
      )}
    >
      <div class="mt-2 flex h-full w-10 shrink-0 items-start">
        <Show when={props.previousMessage?.role !== props.message.role}>
          <Switch>
            <Match when={props.message.role === 'user'}>
              <Tooltip>
                <TooltipTrigger as="div">
                  <img src={user()?.imageUrl} alt="Avatar" class="h-10 w-10 rounded-full" />
                </TooltipTrigger>
                <TooltipContent>Me</TooltipContent>
              </Tooltip>
            </Match>
            <Match when={props.message.role === 'assistant'}>
              <Tooltip>
                <TooltipTrigger as="div">
                  <div class="flex h-10 w-10 flex-shrink-0 place-items-center justify-center overflow-hidden rounded-full bg-primary p-2">
                    <Icon width={300} height={300} class="flex-shrink-0" />
                  </div>
                </TooltipTrigger>
                <TooltipContent>The AI Study Bible</TooltipContent>
              </Tooltip>
            </Match>
          </Switch>
        </Show>
      </div>
      <div class="flex w-full flex-col">
        <Show when={props.message.content} keyed>
          {(content) => <Markdown>{content}</Markdown>}
        </Show>
        <Show
          when={(props.message.toolInvocations?.length ?? 0) > 0 && props.message.toolInvocations}
          keyed
        >
          {(toolInvocations) => (
            <Tools toolInvocations={toolInvocations} addToolResult={props.addToolResult} />
          )}
        </Show>
        <Show when={props.message.data} keyed>
          {(data) => (
            <>
              <Show
                when={
                  props.message.role !== props.nextMessage?.role &&
                  'modelId' in (data as any) &&
                  (data as any).modelId
                }
                keyed
              >
                {(modelId) => {
                  const modelInfo = allModels.find((m) => m.id === modelId.split(':')[1]);
                  if (!modelInfo) {
                    return null;
                  }

                  return (
                    <Tooltip>
                      <TooltipTrigger
                        as={A}
                        href={modelInfo.link}
                        class="mt-2 w-fit rounded-full border p-2 text-xs text-gray-500"
                      >
                        {modelInfo.name}
                      </TooltipTrigger>
                      <TooltipContent>{modelInfo.description}</TooltipContent>
                    </Tooltip>
                  );
                }}
              </Show>
            </>
          )}
        </Show>
      </div>
    </div>
  );
};
