// apps/website/src/lib/components/nav/drawer.svelte
<script lang="ts">
  import { MenuIcon, X } from 'lucide-svelte';
  import Logo from '../branding/logo.svelte';
  import { Button } from '../ui/button';
  import * as Drawer from '../ui/drawer';
</script>

<Drawer.Root direction="left">
  <Drawer.Trigger asChild>
    <Button variant={'ghost'}>
      <MenuIcon size={24} />
    </Button>
  </Drawer.Trigger>
  <Drawer.Content>
    <div class="relative h-dvh w-full">
      <Drawer.Close class="absolute right-5 top-5">
        <X size={20} />
      </Drawer.Close>
      <Drawer.Header>
        <Drawer.Title>
          <a href="/">
            <Logo width={300} height={100} />
          </a>
        </Drawer.Title>
      </Drawer.Header>
    </div>
  </Drawer.Content>
</Drawer.Root>

// apps/www/src/components/navigation/drawer.tsx
import { A, useBeforeLeave } from '@solidjs/router';
import { MenuIcon, X } from 'lucide-solid';
import { createSignal } from 'solid-js';
import LogoSmall from '../branding/logo-small';
import { Button } from '../ui/button';
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from '../ui/drawer';
import { Menu } from './menu';

export const NavigationDrawer = () => {
  const [open, setOpen] = createSignal(false);

  useBeforeLeave(() => {
    setOpen(false);
  });

  return (
    <Drawer side="left" open={open()} onOpenChange={setOpen}>
      <DrawerTrigger as={Button} variant="ghost">
        <MenuIcon size={24} />
      </DrawerTrigger>
      <DrawerContent class="w-1/2">
        <div class="relative h-dvh w-full">
          <DrawerHeader class="flex items-center justify-between">
            <DrawerTitle as={A} href="/">
              <LogoSmall width={150} height={150} />
            </DrawerTitle>
            <DrawerClose as={Button} variant="ghost">
              <X size={24} />
            </DrawerClose>
          </DrawerHeader>
          <div class="block max-w-none space-y-2 p-5">
            <Menu orientation="vertical" />
          </div>
        </div>
      </DrawerContent>
    </Drawer>
  );
};
