// packages/auth-ui/src/routes/(anonymous)/(auth)/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { PUBLIC_WEBSITE_URL } from '$env/static/public';
	import PasswordInput from '$lib/components/auth/PasswordInput.svelte';
	import LogoIcon from '$lib/components/branding/LogoIcon.svelte';
	import { SolidLineSpinner } from '$lib/components/loading';
	import Icon from '@iconify/svelte';
	import type { ActionData, SubmitFunction } from './$types';

	export let form: ActionData;

	let isMobile = false;
	let isLoading = false;
	let alert:
		| {
				type: 'error' | 'success';
				text: string;
		  }
		| undefined = undefined;

	const submit: SubmitFunction = () => {
		isLoading = true;
		return async ({ update }) => {
			isLoading = false;
			await update();
		};
	};

	$: if ($page.url.searchParams.get('resetPassword') === 'success') {
		alert = {
			type: 'success',
			text: 'Your password has been reset. Please login with your new password.'
		};
	}
	$: if ($page.url.searchParams.get('error')) {
		alert = {
			type: 'error',
			text: $page.url.searchParams.get('error')!
		};
	}
	$: if ($page.url.searchParams.get('success')) {
		alert = {
			type: 'success',
			text: $page.url.searchParams.get('success')!
		};
	}
	$: if ($page.url.searchParams.get('mobile') === 'true') {
		isMobile = true;
	}

	$: if (form?.success) {
		goto(form.success.redirect);
	}

	$: if (form?.errors?.banner) {
		alert = {
			type: 'error',
			text: form.errors.banner
		};
	}

	$: alert && setTimeout(() => (alert = undefined), 10000);
</script>

<svelte:head>
	<title>Login to RevelationsAI</title>
</svelte:head>

<div
	class="relative flex flex-col w-full px-5 pt-3 pb-10 bg-white shadow-xl lg:w-1/3 lg:h-full lg:place-content-center lg:px-20 md:w-1/2 sm:w-2/3"
>
	{#if isLoading}
		<div class="absolute left-0 right-0 flex justify-center place-items-center -top-20 lg:top-20">
			<SolidLineSpinner size="md" colorscheme={'dark'} />
		</div>
	{/if}
	{#if alert}
		<div class="absolute left-0 right-0 flex justify-center place-items-center -top-20 lg:top-20">
			<div
				class={`w-5/6 px-4 py-2 mx-auto text-center text-white rounded-xl lg:text-xl ${
					alert.type === 'error' ? 'bg-red-500' : 'bg-green-500'
				}`}
			>
				{alert.text}
			</div>
		</div>
	{/if}
	<div class="flex flex-col">
		<LogoIcon class="mx-auto my-8 rounded-full shadow-xl" />
		<div class="flex flex-col w-full space-y-3 text-center">
			<form class="flex flex-col w-full" method="POST" action="?/social" use:enhance={submit}>
				<input type="hidden" name="mobile" value={isMobile} />
				<input type="hidden" name="provider" value="google" />
				<button
					type="submit"
					class="w-full px-4 py-2 font-medium text-white rounded bg-slate-700 hover:shadow-xl hover:bg-slate-900"
				>
					<Icon icon="fa6-brands:google" class="inline-block mr-2 text-white" />
					Login with Google
				</button>
			</form>
			<form class="flex flex-col w-full" method="POST" action="?/social" use:enhance={submit}>
				<input type="hidden" name="mobile" value={isMobile} />
				<input type="hidden" name="provider" value="apple" />
				<button
					type="submit"
					class="w-full px-4 py-2 font-medium text-white rounded bg-slate-700 hover:shadow-xl hover:bg-slate-900"
				>
					<Icon icon="fa6-brands:apple" class="inline-block mr-2 text-white" />
					Login with Apple
				</button>
			</form>
		</div>
		<div class="divider">OR</div>
		<form class="flex flex-col w-full" method="POST" action="?/credentials" use:enhance={submit}>
			<input type="hidden" name="mobile" value={isMobile} />
			<input
				id="email"
				name="email"
				type="email"
				class="w-full px-2 py-2 mb-3 border shadow-xl outline-none focus:outline-none"
				placeholder="Email address"
			/>
			<PasswordInput class="w-full shadow-xl mb-3" />
			<button
				type="submit"
				class="w-full px-4 py-2 font-medium text-white rounded bg-slate-700 hover:shadow-xl hover:bg-slate-900 mb-3"
			>
				Login with Email
			</button>
			<div class="flex flex-col space-y-1 text-sm text-center text-gray-500">
				<a href="/register" class="hover:underline"> Don't have an account? Register here. </a>
				<a href="/forgot-password" class="hover:underline">Forgot your password?</a>
				<a href={`${PUBLIC_WEBSITE_URL}/privacy-policy`} class="hover:underline">Privacy Policy</a>
			</div>
		</form>
	</div>
</div>

// packages/web/src/app/(fullpage)/login/page.tsx
"use client";

import { DarkLogo } from "@components/branding";
import { useUser } from "@hooks/user";
import { signIn } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { FaFacebookF } from "react-icons/fa";
import { FcGoogle } from "react-icons/fc";

export default function LoginPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const user = useUser();
  const emailInputRef = useRef<HTMLInputElement>(null);
  const [alert, setAlert] = useState<string | null>(null);

  if (user) {
    router.replace(searchParams.get("redirect") ?? "/");
  }

  const handleLogin = async (id: string) => {
    try {
      if (id === "email") {
        if (!emailInputRef.current?.value) {
          throw new Error("Email input is empty");
        }
        signIn("email", {
          email: emailInputRef.current?.value ?? "",
        });
      } else if (id === "google") {
        signIn("google");
      } else if (id === "facebook") {
        signIn("facebook");
      } else {
        throw new Error(`Invalid login method: ${id}`);
      }
    } catch (error: any) {
      setAlert(error.message);
    }
  };

  useEffect(() => {
    if (alert) {
      setTimeout(() => {
        setAlert(null);
      }, 5000);
    }
  }, [alert]);

  return (
    <div className="relative flex flex-col w-2/3 px-5 pt-6 pb-10 bg-white shadow-lg lg:w-1/3 lg:h-full lg:place-content-center lg:px-20 bg-opacity-80 md:w-1/2">
      {alert && (
        <div className="absolute left-0 right-0 flex top-4 lg:top-20">
          <div className="px-4 py-2 mx-auto text-white bg-red-500 border border-red-500 rounded-xl lg:text-xl lg:bg-transparent lg:text-red-500">
            {alert}
          </div>
        </div>
      )}
      <div className="flex flex-col">
        <div className="items-center px-3 py-2 mx-auto mb-5 text-center border rounded-full border-slate-400 lg:mb-10 lg:py-4 lg:px-6">
          <DarkLogo size="2xl" />
        </div>
        <h1 className="mb-2 text-2xl font-bold text-center">Please Log In</h1>
        <div className="divide-y divide-gray-600">
          <div className="w-full pb-4 space-y-3">
            <button
              className="w-full px-4 py-2 font-bold bg-white border rounded text-google hover:shadow-xl border-google"
              onClick={() => signIn("google")}
            >
              <FcGoogle className="inline-block mr-2" />
              Login with Google
            </button>
            <button
              className="w-full px-4 py-2 font-bold text-white rounded bg-facebook hover:shadow-xl"
              onClick={() => signIn("facebook")}
            >
              <FaFacebookF className="inline-block mr-2 text-white" />
              Login with Facebook
            </button>
          </div>
          <div className="container pt-4 space-y-3">
            <input
              className="w-full h-8 px-2 rounded-md outline outline-slate-400"
              placeholder="Email"
              ref={emailInputRef}
            />
            <button
              className="w-full px-4 py-2 font-bold text-white rounded bg-slate-700 hover:shadow-xl"
              onClick={() => {
                handleLogin("email");
              }}
            >
              Login with Email
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
