// packages/web/src/components/devotion/Sidebar.tsx
"use client";

import { SolidLineSpinner } from "@components/loading";
import { Devotion } from "@core/model";
import { useDevotions } from "@hooks/devotion";
import Moment from "moment";
import Link from "next/link";
import { Dispatch, SetStateAction, useEffect, useState } from "react";
import { BsArrowLeftShort } from "react-icons/bs";

export function Sidebar({
  activeDevoId,
  initDevos,
  isOpen,
  setIsOpen,
}: {
  activeDevoId: string;
  initDevos?: Devotion[];
  isOpen: boolean;
  setIsOpen: Dispatch<SetStateAction<boolean>>;
}) {
  const [isLoadingInitial, setIsLoadingInitial] = useState(true);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const { devos, isLoading, limit, setLimit, mutate } = useDevotions(
    "devotions-sidebar",
    initDevos,
    {
      limit: 7,
    }
  );

  const handleGetMoreDevos = () => {
    setLimit(limit + 5);
    mutate();
  };

  useEffect(() => {
    if (devos.length === 0 && isLoading) {
      setIsLoadingInitial(true);
    } else {
      setIsLoadingInitial(false);
    }
  }, [devos, isLoading]);

  useEffect(() => {
    if (devos.length <= limit && isLoading) {
      setIsLoadingMore(true);
    } else {
      setIsLoadingMore(false);
    }
  }, [devos, isLoading, limit]);

  return (
    <div
      className={`absolute flex h-full max-h-full bg-slate-700 border-t-2 duration-300 z-30 lg:w-1/4 lg:static ${
        isOpen ? "w-full" : "w-0"
      }`}
    >
      <div className="relative flex flex-col w-full h-full">
        <div
          className={`absolute top-2 p-1 z-40 rounded-full bg-white border border-slate-700 cursor-pointer duration-300 lg:hidden ${
            isOpen ? "rotate-0 right-2" : "rotate-180 -right-10 opacity-75"
          }`}
          onClick={() => setIsOpen(!isOpen)}
        >
          <BsArrowLeftShort className="text-xl" />
        </div>
        <div
          className={`h-full w-full overflow-y-scroll py-4 px-3 text-white lg:px-6 lg:visible ${
            isOpen ? "visible" : "invisible"
          }`}
        >
          <h1 className="px-2 mb-3 text-2xl font-bold">All Devotions</h1>
          <div className="flex flex-col content-center w-full space-y-2">
            {isLoadingInitial && (
              <div className="flex justify-center w-full">
                <div className="flex items-center justify-center py-5">
                  <SolidLineSpinner size="lg" colorscheme={"light"} />
                </div>
              </div>
            )}
            {devos.map((devo) => (
              <div
                key={devo.id}
                className={`px-3 py-1 rounded-md cursor-pointer duration-200 hover:bg-slate-900 ${
                  devo.id === activeDevoId && "bg-slate-800"
                }`}
              >
                <Link
                  href={`/devotions/${devo.id}`}
                  className="flex flex-col text-lg truncate"
                >
                  <div>{Moment(devo.createdAt).format("MMMM Do YYYY")}</div>
                  <div className="text-xs">
                    {devo.bibleReading.split(" - ")[0]}
                  </div>
                </Link>
              </div>
            ))}
            {isLoadingMore && (
              <div className="flex justify-center w-full">
                <div className="flex items-center justify-center py-5">
                  <SolidLineSpinner size="md" colorscheme={"light"} />
                </div>
              </div>
            )}
            {devos.length >= limit && !isLoadingMore && (
              <button
                className="flex justify-center py-2 text-center border border-white rounded-lg hover:bg-slate-900"
                onClick={handleGetMoreDevos}
              >
                View more
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/website/src/lib/components/admin/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import Icon from '@iconify/svelte';

	let isOpen = false;
	let activePath: string | undefined = undefined;

	const tools: {
		name: string;
		icon: string;
		path: string;
	}[] = [
		{
			name: 'Index File',
			icon: 'mdi:file-find',
			path: '/admin/file-index'
		},
		{
			name: 'Index Website',
			icon: 'mdi:web',
			path: '/admin/website-index'
		},
		{
			name: 'Index Webpage',
			icon: 'mdi:web',
			path: '/admin/webpage-index'
		}
	];

	$: if ($page.url.pathname) {
		activePath = $page.url.pathname;
		isOpen = false;
	}
</script>

<div
	class={`absolute flex h-full max-h-full bg-slate-700 border-t-2 duration-300 z-30 lg:w-1/4 lg:static ${
		isOpen ? 'w-full' : 'w-0'
	}`}
>
	<div class="relative flex flex-col w-full h-full">
		<button
			class={`absolute top-2 p-1 z-40 rounded-full bg-white border border-slate-700 cursor-pointer duration-300 lg:hidden ${
				isOpen ? 'rotate-0 right-2' : 'rotate-180 -right-10 opacity-75'
			}`}
			on:click|preventDefault={() => (isOpen = !isOpen)}
		>
			<Icon icon="formkit:arrowleft" height={20} width={20} />
		</button>
		<div
			class={`h-full w-full overflow-y-scroll py-4 px-3 text-white lg:px-6 lg:visible ${
				isOpen ? 'visible' : 'invisible'
			}`}
		>
			<h1 class="px-2 mb-3 text-2xl font-bold">Admin Utilities</h1>
			<div class="flex flex-col justify-center w-full space-y-3">
				{#each tools as tool}
					<div
						class={`flex px-3 py-2 rounded-xl cursor-pointer hover:bg-slate-900 ${
							activePath === tool.path ? 'bg-slate-900' : ''
						}`}
					>
						<Icon icon={tool.icon} class="mr-2 text-xl" />
						<a href={tool.path}>{tool.name}</a>
					</div>
				{/each}
			</div>
		</div>
	</div>
</div>
