// packages/website/src/routes/(fullpage)/(anonymous)/auth/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { page } from '$app/stores';
	import PasswordInput from '$lib/components/auth/PasswordInput.svelte';
	import Logo from '$lib/components/branding/Logo.svelte';
	import { SolidLineSpinner } from '$lib/components/loading';
	import Icon from '@iconify/svelte';
	import type { ActionData, SubmitFunction } from './$types';

	export let form: ActionData;

	let isLoading = false;
	let alertMessage:
		| {
				type: 'error' | 'success';
				text: string;
		  }
		| undefined = undefined;

	const submit: SubmitFunction = () => {
		isLoading = true;
		return async ({ update }) => {
			isLoading = false;
			await update();
		};
	};

	$: if ($page.url.searchParams.get('reset-password') === 'success') {
		alertMessage = {
			type: 'success',
			text: 'Your password has been reset. Please login with your new password.'
		};
	}
	$: if ($page.url.searchParams.get('error')) {
		alertMessage = {
			type: 'error',
			text: $page.url.searchParams.get('error')!
		};
	}
	$: if ($page.url.searchParams.get('success')) {
		alertMessage = {
			type: 'success',
			text: $page.url.searchParams.get('success')!
		};
	}

	$: if (form?.errors?.banner) {
		alertMessage = {
			type: 'error',
			text: form.errors.banner
		};
	}

	$: alertMessage && setTimeout(() => (alertMessage = undefined), 10000);
</script>

<div
	class="relative flex flex-col w-full px-5 pt-3 pb-10 bg-white shadow-xl lg:w-1/3 lg:h-full lg:place-content-center lg:px-20 md:w-1/2 sm:w-2/3"
>
	{#if isLoading}
		<div class="absolute left-0 right-0 flex justify-center place-items-center -top-20 lg:top-20">
			<SolidLineSpinner size="md" colorscheme={'dark'} />
		</div>
	{/if}
	{#if alertMessage}
		<div class="absolute left-0 right-0 flex justify-center place-items-center -top-20 lg:top-20">
			<div
				class={`w-5/6 px-4 py-2 mx-auto text-center text-white rounded-xl lg:text-xl ${
					alertMessage.type === 'error' ? 'bg-red-500' : 'bg-green-500'
				}`}
			>
				{alertMessage.text}
			</div>
		</div>
	{/if}
	<div class="flex flex-col">
		<div
			class="items-center px-3 py-2 mx-auto my-8 text-center border rounded-lg border-slate-400 lg:mb-10 lg:py-4 lg:px-6"
		>
			<Logo size="2xl" colorscheme={'dark'} />
		</div>
		<div class="divide-y divide-gray-600">
			<div class="flex flex-col w-full pb-4 space-y-3 text-center">
				<form class="flex flex-col w-full" method="POST" action="?/social" use:enhance={submit}>
					<input type="hidden" name="provider" value="google" />
					<button
						type="submit"
						class="w-full px-4 py-2 font-bold text-white rounded bg-slate-700 hover:shadow-xl hover:bg-slate-900"
					>
						<Icon icon="fa6-brands:google" class="inline-block mr-2 text-white" />
						Login with Google
					</button>
				</form>
				<form class="flex flex-col w-full" method="POST" action="?/social" use:enhance={submit}>
					<input type="hidden" name="provider" value="facebook" />
					<button
						type="submit"
						class="w-full px-4 py-2 font-bold text-white rounded bg-slate-700 hover:shadow-xl hover:bg-slate-900"
					>
						<Icon icon="fa6-brands:facebook-f" class="inline-block mr-2 text-white" />
						Login with Facebook
					</button>
				</form>
			</div>
			<form
				class="flex flex-col w-full pt-4 space-y-3"
				method="POST"
				action="?/email"
				use:enhance={submit}
			>
				<input
					id="email"
					name="email"
					type="email"
					class="w-full px-2 py-2 border shadow-xl outline-none focus:outline-none"
					placeholder="Email address"
				/>
				<PasswordInput class="w-full shadow-xl" />
				<button
					type="submit"
					class="w-full px-4 py-2 font-bold text-white rounded bg-slate-700 hover:shadow-xl hover:bg-slate-900"
				>
					Login with Email
				</button>
				<div class="flex justify-between text-sm text-gray-500">
					<a href="/auth/register" class="hover:underline">
						Don't have an account? Register here.
					</a>
					<a href="/auth/forgot-password" class="hover:underline">Forgot your password?</a>
				</div>
			</form>
		</div>
	</div>
</div>

// packages/frontend/app/(fullpage)/login/page.tsx
"use client";

import { SolidLineSpinner } from "@/components";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useSessionContext } from "supertokens-auth-react/recipe/session";
import { emailPasswordSignIn } from "supertokens-auth-react/recipe/thirdpartyemailpassword";

export default function LoginPage() {
  const session = useSessionContext();
  const router = useRouter();
  const emailRef = useRef<HTMLInputElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);
  const showPasswordRef = useRef<HTMLButtonElement>(null);
  const [showPassword, setShowPassword] = useState<boolean>(false);
  const [invalidCredentials, setInvalidCredentials] = useState<boolean>(false);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [loginError, setLoginError] = useState<string | null>(null);

  const handleShowPassword = () => {
    if (passwordRef.current?.type === "password") {
      passwordRef.current.type = "text";
      setShowPassword(true);
    } else {
      passwordRef.current!.type = "password";
      setShowPassword(false);
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    try {
      let response = await emailPasswordSignIn({
        formFields: [
          {
            id: "email",
            value: emailRef.current!.value,
          },
          {
            id: "password",
            value: passwordRef.current!.value,
          },
        ],
      });
      console.log(JSON.stringify(response));
      if (response.status === "FIELD_ERROR") {
        response.formFields.map((field) => {
          setFieldErrors((prev) => ({ ...prev, [field.id]: field.error }));
        });
      } else if (response.status === "WRONG_CREDENTIALS_ERROR") {
        setInvalidCredentials(true);
      } else {
        router.push("/");
      }
    } catch (error: any) {
      setLoginError(error.message);
    }
  };

  const clearErrors = () => {
    setFieldErrors({});
    setInvalidCredentials(false);
  };

  useEffect(() => {
    emailRef.current?.focus();
  }, []);

  if (session.loading) {
    return <SolidLineSpinner height={20} width={20} color="slate" />;
  }

  if (session.doesSessionExist) {
    router.push("/");
  }

  return (
    <div className="w-2/3 shadow-lg bg-white py-4 px-2">
      <h2 className="text-center text-xl">Login</h2>
      {loginError && (
        <div className="bg-red-400 text-white text-sm text-center px-2 py-1 rounded-lg">
          Oops! An error occurred signing in: {loginError}. Please try again
          later.
        </div>
      )}
      {invalidCredentials && (
        <div className="text-red-500 text-sm text-center">
          Invalid credentials
        </div>
      )}
      <form className="flex flex-col px-3 space-y-3" onSubmit={handleSubmit}>
        <label className="flex flex-col">
          <span className="text-sm">Email</span>
          <input
            ref={emailRef}
            className="border border-gray-300 rounded-md p-1 focus:outline-none"
            type="email"
            placeholder="Email"
            onChange={clearErrors}
          />
          {fieldErrors.email && (
            <div className="text-red-500 text-sm">{fieldErrors.email}</div>
          )}
        </label>
        <label className="flex flex-col">
          <span className="text-sm">Password</span>
          <div className="flex w-full rounded-md p-1 border border-gray-300">
            <input
              ref={passwordRef}
              className="w-full focus:outline-none"
              type="password"
              placeholder="Password"
              onChange={clearErrors}
            />
            <button
              ref={showPasswordRef}
              onClick={handleShowPassword}
              className="border-l pl-1 border-l-slate-300 text-xs"
            >
              {showPassword ? "Hide" : "Show"}
            </button>
          </div>
          {fieldErrors.password && (
            <div className="text-red-500 text-sm">{fieldErrors.password}</div>
          )}
        </label>
        <button
          className="bg-blue-300 hover:bg-blue-400 text-white font-bold py-2 px-4 rounded"
          type="submit"
        >
          Login
        </button>
      </form>
      <div className="text-center mt-2">OR</div>
      <div className="flex flex-col p-3 space-y-3">
        <button className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
          Login with Google
        </button>
        <button className="bg-blue-600 hover:bg-blue-800 text-white font-bold py-2 px-4 rounded">
          Login with Facebook
        </button>
      </div>
      <div className="px-3">
        <p>
          Don't have an account?{" "}
          <Link
            href={"/signup"}
            className="text-blue-400 hover:text-blue-600 underline"
          >
            Signup
          </Link>
        </p>
      </div>
    </div>
  );
}
