// packages/web/src/components/devo/Sidebar.tsx
"use client";

import { Devo } from "@types";
import Moment from "moment";
import Link from "next/link";
import { useState } from "react";
import { BsArrowRightShort } from "react-icons/bs";

export function Sidebar({
  activeDevoId,
  devos,
}: {
  activeDevoId: string;
  devos: Devo[];
}) {
  const [isOpen, setIsOpen] = useState(true);
  return (
    <div
      className={`h-full max-h-full grow-0 bg-slate-700 border-t-2 relative duration-300 ${
        isOpen ? "w-52" : "w-0"
      }`}
    >
      <div
        className={`absolute top-2 p-1 z-50 rounded-full bg-white border border-slate-700 cursor-pointer duration-300 ${
          isOpen ? "rotate-0 -right-3.5" : "rotate-180 -right-10 opacity-75"
        }`}
        onClick={() => setIsOpen(!isOpen)}
      >
        <BsArrowRightShort className="text-xl" />
      </div>
      <ul
        className={`mt-2 mx-3 space-y-1 ${
          isOpen ? "scale-100" : "scale-0"
        } duration-300 text-white`}
      >
        {devos.map((devo) => (
          <li
            key={devo.id}
            className={`${
              devo.id === activeDevoId && "bg-slate-300 text-slate-700"
            } px-2 py-1 rounded-md cursor-pointer duration-200 hover:bg-slate-300 hover:text-slate-700`}
          >
            <Link href={`/devos/${devo.id}`} className="flex flex-col">
              <div>{Moment(devo.createdAt).format("MMMM Do YYYY")}</div>
              <div className="text-xs">{devo.subject.split(" - ")[0]}</div>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

// packages/website/src/lib/components/devotion/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { getDevotions } from '$lib/services/devotion';
	import type { Devotion } from '@core/model';
	import Icon from '@iconify/svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import Moment from 'moment';
	import { SolidLineSpinner } from '../loading';

	export let initDevos: Devotion[] = [];
	export let activeDevoId: string;

	let isOpen = false;
	let limit = 5;
	let devotions: Devotion[] = [];
	let isLoadingInitial = false;
	let isLoadingMore = false;

	$: query = createQuery({
		queryKey: ['devos'],
		queryFn: () => getDevotions({ limit }).then((r) => r.devotions),
		initialData: initDevos
	});

	$: query?.subscribe(({ data, isLoading, isFetching }) => {
		devotions = data ?? [];

		if ((isLoading || isFetching) && devotions.length === 0) {
			isLoadingInitial = true;
		} else {
			isLoadingInitial = false;
		}

		if ((isLoading || isFetching) && limit > devotions.length) {
			isLoadingMore = true;
		} else {
			isLoadingMore = false;
		}
	});

	$: if ($page.url.pathname) isOpen = false;
</script>

<div
	class={`absolute flex h-full max-h-full bg-slate-700 border-t-2 duration-300 z-30 lg:w-1/4 lg:static ${
		isOpen ? 'w-full' : 'w-0'
	}`}
>
	<div class="relative flex flex-col w-full h-full">
		<button
			class={`absolute top-2 p-1 z-40 rounded-full bg-white border border-slate-700 cursor-pointer duration-300 lg:hidden ${
				isOpen ? 'rotate-0 right-2' : 'rotate-180 -right-10 opacity-75'
			}`}
			on:click|preventDefault={() => (isOpen = !isOpen)}
		>
			<Icon icon="formkit:arrowleft" height={20} width={20} />
		</button>
		<div
			class={`h-full w-full overflow-y-scroll py-4 px-3 text-white lg:px-6 lg:visible ${
				isOpen ? 'visible' : 'invisible'
			}`}
		>
			<h1 class="px-2 mb-3 text-2xl font-bold">All Devotions</h1>
			<div class="flex flex-col content-center w-full space-y-2">
				{#if isLoadingInitial}
					<div class="flex justify-center w-full">
						<div class="flex items-center justify-center py-5">
							<SolidLineSpinner size="lg" colorscheme={'light'} />
						</div>
					</div>
				{/if}
				{#if $query.isSuccess}
					{#each devotions as devotion (devotion.id)}
						<div
							class={`px-3 py-1 rounded-md cursor-pointer duration-200 hover:bg-slate-900 ${
								devotion.id === activeDevoId && 'bg-slate-800'
							}`}
						>
							<a href={`/devotions/${devotion.id}`} class="flex flex-col text-lg truncate">
								<div>{Moment(devotion.createdAt).format('MMMM Do YYYY')}</div>
								<div class="text-xs">
									{devotion.bibleReading.split(' - ')[0]}
								</div>
							</a>
						</div>
					{/each}
					{#if !isLoadingMore && devotions.length >= limit}
						<button
							class="flex justify-center py-2 text-center border border-white rounded-lg hover:bg-slate-900"
							on:click|preventDefault={() => (limit = limit + 5)}
						>
							View more
						</button>
					{:else if isLoadingMore}
						<div class="flex justify-center w-full">
							<div class="flex items-center justify-center py-5">
								<SolidLineSpinner size="md" colorscheme={'light'} />
							</div>
						</div>
					{/if}
				{:else if $query.isError}
					<div>
						Error fetching devotions: {$query.error}
					</div>
				{/if}
			</div>
		</div>
	</div>
</div>
