// packages/web/src/components/devotion/Sidebar.tsx
"use client";

import { useDevotions } from "@hooks/devotion";
import { Devotion } from "@revelationsai/core/database/model";
import Moment from "moment";
import Link from "next/link";
import { Dispatch, SetStateAction, useEffect, useState } from "react";
import { BsArrowLeftShort } from "react-icons/bs";
import { SolidLineSpinner } from "..";

export function Sidebar({
  activeDevoId,
  initDevos,
  isOpen,
  setIsOpen,
}: {
  activeDevoId: string;
  initDevos?: Devotion[];
  isOpen: boolean;
  setIsOpen: Dispatch<SetStateAction<boolean>>;
}) {
  const [isLoadingInitial, setIsLoadingInitial] = useState(true);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const { devos, isLoading, limit, setLimit, mutate } = useDevotions(
    initDevos,
    {
      limit: 7,
    }
  );

  const handleGetMoreDevos = () => {
    setLimit(limit + 5);
    mutate();
  };

  useEffect(() => {
    if (devos.length === 0 && isLoading) {
      setIsLoadingInitial(true);
    } else {
      setIsLoadingInitial(false);
    }
  }, [devos, isLoading]);

  useEffect(() => {
    if (devos.length <= limit && isLoading) {
      setIsLoadingMore(true);
    } else {
      setIsLoadingMore(false);
    }
  }, [devos, isLoading, limit]);

  return (
    <div
      className={`absolute flex h-full max-h-full bg-slate-700 border-t-2 duration-300 z-30 lg:w-1/4 lg:static ${
        isOpen ? "w-full" : "w-0"
      }`}
    >
      <div className="relative flex flex-col w-full h-full">
        <div
          className={`absolute top-2 p-1 z-40 rounded-full bg-white border border-slate-700 cursor-pointer duration-300 lg:hidden ${
            isOpen ? "rotate-0 right-2" : "rotate-180 -right-10 opacity-75"
          }`}
          onClick={() => setIsOpen(!isOpen)}
        >
          <BsArrowLeftShort className="text-xl" />
        </div>
        <div
          className={`h-full w-full overflow-y-scroll py-4 px-3 text-white lg:px-6 lg:visible ${
            isOpen ? "visible" : "invisible"
          }`}
        >
          <h1 className="px-2 mb-3 text-2xl font-bold">All Devotions</h1>
          <div className="flex flex-col content-center w-full space-y-2">
            {isLoadingInitial && (
              <div className="flex justify-center w-full">
                <div className="flex items-center justify-center py-5">
                  <SolidLineSpinner size="lg" colorscheme={"light"} />
                </div>
              </div>
            )}
            {devos.map((devo) => (
              <div
                key={devo.id}
                className={`px-3 py-1 rounded-md cursor-pointer duration-200 hover:bg-slate-900 ${
                  devo.id === activeDevoId && "bg-slate-800"
                }`}
              >
                <Link
                  href={`/devotions/${devo.id}`}
                  className="flex flex-col text-lg truncate"
                >
                  <div>{Moment(devo.createdAt).format("MMMM Do YYYY")}</div>
                  <div className="text-xs">
                    {devo.bibleReading.split(" - ")[0]}
                  </div>
                </Link>
              </div>
            ))}
            {isLoadingMore && (
              <div className="flex justify-center w-full">
                <div className="flex items-center justify-center py-5">
                  <SolidLineSpinner size="md" colorscheme={"light"} />
                </div>
              </div>
            )}
            {devos.length >= limit && !isLoadingMore && (
              <button
                className="flex justify-center py-2 text-center border border-white rounded-lg hover:bg-slate-900"
                onClick={handleGetMoreDevos}
              >
                View more
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/website-old/src/lib/components/devotion/Sidebar.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import Icon from '@iconify/svelte';
  import { searchForDevotions } from '@revelationsai/client/services/devotion';
  import type { Query } from '@revelationsai/core/database/helpers';
  import type { Devotion } from '@revelationsai/core/model/devotion';
  import { toTitleCase } from '@revelationsai/core/util/string';
  import { createInfiniteQuery } from '@tanstack/svelte-query';
  import Day from 'dayjs';
  import { derived, writable } from 'svelte/store';

  export let initDevos: Devotion[] = [];
  export let activeDevoId: string;

  let isOpen = false;
  let devotions = initDevos;
  let loadingDevoId: string | undefined = undefined;

  const queryString = writable('');

  const fetchDevotions = async ({
    pageParam = 1,
    query = {}
  }: {
    pageParam: number;
    query: Query;
  }) => {
    return await searchForDevotions({
      limit: 7,
      page: pageParam,
      query
    }).then((r) => r.devotions);
  };

  let query = createInfiniteQuery(
    derived(queryString, ($queryString) => {
      let searchQuery: Query = {};
      if ($queryString) {
        searchQuery = {
          OR: [
            {
              iLike: {
                column: 'topic',
                placeholder: `%${$queryString}%`
              }
            },
            {
              iLike: {
                column: 'bibleReading',
                placeholder: `%${$queryString}%`
              }
            }
          ]
        };
      }
      return {
        queryKey: ['infinite-devotions', $queryString],
        queryFn: ({ pageParam }: { pageParam: number }) =>
          fetchDevotions({ pageParam, query: searchQuery }),
        getNextPageParam: (lastPage: Devotion[], pages: Devotion[][]) => {
          if (lastPage.length < 7) return undefined;
          return pages.length + 1;
        },
        initialPageParam: 1,
        initialData: {
          pages: [devotions],
          pageParams: [1]
        }
      };
    })
  );

  query.subscribe(({ data, isSuccess }) => {
    if (isSuccess) {
      devotions = data.pages.flat();
    }
  });

  $: if ($page.url.pathname) {
    isOpen = false;
    loadingDevoId = undefined;
  }

  $: if (loadingDevoId) activeDevoId = loadingDevoId;
</script>

<nav
  class={`absolute z-30 flex h-full flex-shrink-0 flex-grow-0 border-t-2 bg-slate-700 duration-300 lg:static lg:w-1/4 ${
    isOpen ? 'w-full' : 'w-0'
  }`}
>
  <div class="relative flex h-full w-full flex-col">
    <button
      class={`absolute top-2 z-50 cursor-pointer rounded-full border border-slate-700 bg-white p-1 duration-300 lg:hidden ${
        isOpen ? 'right-2 rotate-0' : '-right-10 rotate-180 opacity-75'
      }`}
      on:click|preventDefault={() => (isOpen = !isOpen)}
    >
      <Icon icon="formkit:arrowleft" height={20} width={20} />
    </button>
    <div
      class={`h-full w-full overflow-y-auto px-6 py-4 text-white lg:visible lg:px-2 ${
        isOpen ? 'visible' : 'invisible'
      }`}
    >
      <h1 class="mb-3 px-2 text-2xl font-medium">All Devotions</h1>
      <div class="flex w-full flex-col content-center space-y-2">
        {#if $query.isLoading}
          <div class="flex w-full justify-center">
            <div class="flex items-center justify-center py-5">
              <span class="loading loading-spinner loading-lg" />
            </div>
          </div>
        {:else}
          <div
            class="flex w-full place-items-center justify-center rounded-lg bg-slate-800 px-2 py-1"
          >
            <Icon icon="mdi:magnify" height={20} width={20} />
            <input
              id="search"
              name="search"
              class="flex-1 rounded-lg bg-transparent px-2 py-1 focus:border-none focus:outline-none focus:ring-0"
              placeholder="Search devotions"
              autocomplete="off"
              bind:value={$queryString}
            />
            {#if $queryString}
              <button
                class="hover:text-red-500"
                on:click|preventDefault={() => ($queryString = '')}
              >
                <Icon icon="pajamas:clear" height={15} width={15} />
              </button>
            {/if}
          </div>
        {/if}
        {#each devotions as devotion (devotion.id)}
          <div
            class={`flex w-full cursor-pointer place-items-center justify-between truncate rounded-md px-3 py-1 duration-200 hover:bg-slate-900 active:bg-slate-900 ${
              devotion.id === activeDevoId && 'bg-slate-800'
            }`}
          >
            <button
              class="flex w-full flex-col truncate text-lg"
              on:click|preventDefault={async () => {
                if (activeDevoId === devotion.id) {
                  isOpen = false;
                  return;
                } else {
                  loadingDevoId = devotion.id;
                  await goto(`/devotions/${devotion.id}`);
                }
              }}
            >
              <div>
                {Day(devotion.createdAt).format('MMMM D, YYYY')}
              </div>
              <div class="text-xs">
                {toTitleCase(devotion.topic)} - {devotion.bibleReading.split(' - ')[0]}
              </div>
            </button>
            <div class="flex place-items-center justify-center">
              {#if loadingDevoId === devotion.id}
                <div class="flex place-items-center justify-center">
                  <span class="loading loading-spinner loading-xs" />
                </div>
              {/if}
            </div>
          </div>
        {/each}
        {#if $query.hasNextPage && !$query.isFetchingNextPage}
          <button
            class="flex justify-center rounded-lg border border-white py-2 text-center hover:bg-slate-900"
            on:click|preventDefault={() => $query.fetchNextPage()}
          >
            View more
          </button>
        {:else if $query.isFetchingNextPage}
          <div class="flex w-full justify-center">
            <div class="flex items-center justify-center py-5">
              <span class="loading loading-spinner loading-md" />
            </div>
          </div>
        {/if}
      </div>
    </div>
  </div>
</nav>
