// apps/www/app/contexts/bible.tsx
import type { Bible, Book, Chapter, Verse } from '@/schemas/bibles/types';
import { type ReactNode, createContext, useContext, useRef } from 'react';
import type { StoreApi } from 'zustand';
import { useStore } from 'zustand';
import { persist } from 'zustand/middleware';
import { createStore } from 'zustand/vanilla';

export type BibleState = {
  bible: Bible | null;
  book: Book | null;
  chapter: Omit<Chapter, 'content'> | null;
  verse: Omit<Verse, 'content'> | null;
};

export type BibleActions = {
  setBible: (bible: Bible | null) => void;
  setBook: (book: Book | null) => void;
  setChapter: (chapter: Omit<Chapter, 'content'> | null) => void;
  setVerse: (verse: Omit<Verse, 'content'> | null) => void;
};

export type BibleStore = BibleState & BibleActions;

export type BibleContextValue = StoreApi<BibleStore>;

export const BibleContext = createContext<BibleContextValue | null>(null);

export type BibleProviderProps = {
  bible?: Bible;
  book?: Book;
  chapter?: Omit<Chapter, 'content'>;
  verse?: Omit<Verse, 'content'>;
  children: ReactNode;
};

export const BibleProvider = ({ bible, book, chapter, verse, children }: BibleProviderProps) => {
  const storeRef = useRef<BibleContextValue>(null);
  if (!storeRef.current) {
    storeRef.current = createStore<BibleStore>()(
      persist(
        (set) => ({
          bible: bible ?? null,
          book: book ?? null,
          chapter: chapter ?? null,
          verse: verse ?? null,
          setBible: (bible) => set({ bible }),
          setBook: (book) => set({ book }),
          setChapter: (chapter) => set({ chapter }),
          setVerse: (verse) => set({ verse }),
        }),
        { name: 'bible' },
      ),
    );
  }

  return <BibleContext.Provider value={storeRef.current}>{children}</BibleContext.Provider>;
};

export const useBibleStore = <T = BibleStore>(selector?: (state: BibleStore) => T): T => {
  const bibleStoreContext = useContext(BibleContext);
  if (!bibleStoreContext) {
    throw new Error('useBibleStore must be used within BibleProvider');
  }

  if (!selector) {
    return useStore(bibleStoreContext, (state: BibleStore) => state) as T;
  }

  return useStore(bibleStoreContext, selector);
};

// apps/www/src/contexts/bible.tsx
import type { Bible, Book, Chapter, Verse } from '@/schemas/bibles/types';
import { makePersisted } from '@solid-primitives/storage';
import type { JSXElement } from 'solid-js';
import { createContext, splitProps, useContext } from 'solid-js';
import type { SetStoreFunction, Store } from 'solid-js/store';
import { createStore } from 'solid-js/store';

export type BibleStore = {
  bible: Bible | null;
  book: Book | null;
  chapter: Omit<Chapter, 'content'> | null;
  verse: Omit<Verse, 'content'> | null;
};

export type BibleContextValue = [get: Store<BibleStore>, set: SetStoreFunction<BibleStore>];

export const BibleContext = createContext<BibleContextValue>();

export type BibleProviderProps = {
  bible?: Bible;
  book?: Book;
  chapter?: Omit<Chapter, 'content'>;
  verse?: Omit<Verse, 'content'>;
  children: JSXElement;
};

export const BibleProvider = (props: BibleProviderProps) => {
  const [local, others] = splitProps(props, ['children']);

  const [store, setStore] = makePersisted(
    createStore<BibleStore>({
      bible: others.bible ?? null,
      book: others.book ?? null,
      chapter: others.chapter ?? null,
      verse: others.verse ?? null,
    }),
    { name: 'bible' },
  );

  return (
    <BibleContext.Provider value={[store, setStore] as BibleContextValue}>
      {local.children}
    </BibleContext.Provider>
  );
};

export const useBibleStore = () => {
  const store = useContext(BibleContext);
  if (!store) {
    throw new Error('useBibleStore must be used within a BibleProvider');
  }
  return store;
};
