// apps/web/src/components/ui/avatar.tsx
import * as ImagePrimitive from '@kobalte/core/image';
import type { PolymorphicProps } from '@kobalte/core/polymorphic';
import { splitProps, type ValidComponent } from 'solid-js';
import { cn } from '~/lib/utils';

type AvatarRootProps = ImagePrimitive.ImageRootProps & { class?: string | undefined };

const Avatar = <T extends ValidComponent = 'span'>(props: PolymorphicProps<T, AvatarRootProps>) => {
  const [local, others] = splitProps(props as AvatarRootProps, ['class']);
  return (
    <ImagePrimitive.Root
      class={cn('relative flex size-10 shrink-0 overflow-hidden rounded-full', local.class)}
      {...others}
    />
  );
};

type AvatarImageProps = ImagePrimitive.ImageImgProps & { class?: string | undefined };

const AvatarImage = <T extends ValidComponent = 'img'>(
  props: PolymorphicProps<T, AvatarImageProps>
) => {
  const [local, others] = splitProps(props as AvatarImageProps, ['class']);
  return <ImagePrimitive.Img class={cn('aspect-square size-full', local.class)} {...others} />;
};

type AvatarFallbackProps = ImagePrimitive.ImageFallbackProps & { class?: string | undefined };

const AvatarFallback = <T extends ValidComponent = 'span'>(
  props: PolymorphicProps<T, AvatarFallbackProps>
) => {
  const [local, others] = splitProps(props as AvatarFallbackProps, ['class']);
  return (
    <ImagePrimitive.Fallback
      class={cn('flex size-full items-center justify-center rounded-full bg-muted', local.class)}
      {...others}
    />
  );
};

export { Avatar, AvatarFallback, AvatarImage };

// apps/www/app/components/ui/avatar.tsx
'use client';

import type * as React from 'react';
import * as AvatarPrimitive from '@radix-ui/react-avatar';

import { cn } from '@/www/lib/utils';

function Avatar({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Root>) {
  return (
    <AvatarPrimitive.Root
      data-slot='avatar'
      className={cn('relative flex size-8 shrink-0 overflow-hidden rounded-full', className)}
      {...props}
    />
  );
}

function AvatarImage({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Image>) {
  return (
    <AvatarPrimitive.Image
      data-slot='avatar-image'
      className={cn('aspect-square size-full', className)}
      {...props}
    />
  );
}

function AvatarFallback({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
  return (
    <AvatarPrimitive.Fallback
      data-slot='avatar-fallback'
      className={cn('flex size-full items-center justify-center rounded-full bg-muted', className)}
      {...props}
    />
  );
}

export { Avatar, AvatarImage, AvatarFallback };
