// apps/www/src/routes/(with-header)/admin/data-sources.tsx
import { db } from '@/core/database';
import { DeleteDataSourceButton } from '@/www/components/admin/data-sources/delete-button';
import { EditDataSourceButton } from '@/www/components/admin/data-sources/edit-button';
import { SyncDataSourceButton } from '@/www/components/admin/data-sources/sync-button';
import { QueryBoundary } from '@/www/components/query-boundary';
import { Button } from '@/www/components/ui/button';
import { DataTable } from '@/www/components/ui/data-table';
import { GET } from '@solidjs/start';
import { createInfiniteQuery } from '@tanstack/solid-query';
import { formatDate } from 'date-fns';
import { Pencil, RefreshCw, Trash } from 'lucide-solid';
import { Show } from 'solid-js';

const getSources = GET(async (input: { offset: number; limit: number }) => {
  'use server';
  const sources = await db.query.dataSources.findMany({
    offset: input.offset,
    limit: input.limit,
  });
  return {
    sources,
    nextCursor: sources.length === input.limit ? input.offset + input.limit : undefined,
  };
});

const SourcesPage = () => {
  const query = createInfiniteQuery(() => ({
    queryKey: ['data-sources'],
    queryFn: ({ pageParam }) => getSources({ offset: pageParam ?? 0, limit: 10 }),
    getNextPageParam: (lastPage) => lastPage.nextCursor,
    initialPageParam: 0,
    refetchInterval: 10000,
  }));

  return (
    <QueryBoundary query={query}>
      {({ pages }) => (
        <div class='flex flex-col gap-4'>
          <DataTable
            columns={[
              { accessorKey: 'id', header: 'ID' },
              { accessorKey: 'type', header: 'Type' },
              { accessorKey: 'name', header: 'Name' },
              {
                accessorKey: 'url',
                header: 'URL',
                cell: (props) => <div class='max-w-52 truncate'>{props.row.getValue('url')}</div>,
              },
              {
                accessorKey: 'syncSchedule',
                header: 'Schedule',
              },
              {
                accessorKey: 'numberOfDocuments',
                header: 'Documents',
              },
              {
                accessorKey: 'lastManualSync',
                header: 'Last Manual Sync',
                cell: (props) =>
                  props.row.getValue('lastManualSync')
                    ? formatDate(props.row.getValue('lastManualSync'), 'MM/dd/yyyy hh:mm a')
                    : 'N/A',
              },
              {
                accessorKey: 'lastAutomaticSync',
                header: 'Last Automatic Sync',
                cell: (props) =>
                  props.row.getValue('lastAutomaticSync')
                    ? formatDate(props.row.getValue('lastAutomaticSync'), 'MM/dd/yyyy hh:mm a')
                    : 'N/A',
              },
              {
                accessorKey: 'id',
                header: 'Actions',
                cell: (props) => (
                  <div class='flex gap-1'>
                    <SyncDataSourceButton
                      variant='ghost'
                      size='icon'
                      dataSource={props.row.original}
                      class='size-8'
                    >
                      <RefreshCw />
                    </SyncDataSourceButton>
                    <EditDataSourceButton
                      variant='ghost'
                      size='icon'
                      dataSource={props.row.original}
                      class='size-8'
                    >
                      <Pencil />
                    </EditDataSourceButton>
                    <DeleteDataSourceButton
                      variant='ghost'
                      size='icon'
                      dataSource={props.row.original}
                      class='size-8'
                    >
                      <Trash />
                    </DeleteDataSourceButton>
                  </div>
                ),
              },
            ]}
            data={pages.flatMap((page) => page.sources)}
          />
          <Show when={query.hasNextPage}>
            <Button onClick={() => query.fetchNextPage()}>Load more</Button>
          </Show>
        </div>
      )}
    </QueryBoundary>
  );
};

export default SourcesPage;

// packages/website/src/routes/(navbar)/(protected)/admin/data-sources/+page.svelte
<script lang="ts">
	import { getDataSources } from '$lib/services/data-source';
	import type { DataSource } from '@core/model/data-source';
	import { createInfiniteQuery } from '@tanstack/svelte-query';
	import type { SvelteComponent } from 'svelte';
	import type { PageData } from './$types';
	import CreateDialog from './CreateDialog.svelte';
	import DataSourceRow from './DataSourceRow.svelte';

	export let data: PageData;

	let createDialog: SvelteComponent | undefined = undefined;
	let dataSources: DataSource[] = [];

	const fetchFn = async ({ pageParam = 1 }) => {
		return await getDataSources({ limit: data.limit, page: pageParam }).then((r) => r.dataSources);
	};

	const query = createInfiniteQuery({
		queryKey: ['infinite-data-sources'],
		queryFn: fetchFn,
		initialPageParam: 1,
		getNextPageParam: (lastPage, pages) => {
			if (lastPage.length < data.limit) return undefined;
			return pages.length + 1;
		},
		initialData: {
			pages: [data.dataSources],
			pageParams: [1]
		},
		refetchInterval: 8000
	});
	query.subscribe(({ data, isSuccess }) => {
		if (isSuccess) {
			dataSources = data.pages.flat();
		}
	});
</script>

<svelte:head>
	<title>Data Sources</title>
</svelte:head>

<div class="flex flex-col w-full h-full p-5 space-y-5">
	<div class="flex space-x-2 place-items-center">
		<h1 class="text-2xl font-medium">Data Sources</h1>
		<button
			class="text-white btn btn-circle btn-xs bg-slate-700 hover:bg-slate-900"
			on:click={() => createDialog?.show()}>+</button
		>
		<CreateDialog bind:this={createDialog} />
	</div>
	<div class="w-full h-full overflow-auto">
		<table class="table whitespace-normal table-xs">
			<thead>
				<tr>
					<th />
					<th>ID</th>
					<th>Name</th>
					<th>Type</th>
					<th>Sync Schedule</th>
					<th>Last Sync</th>
					<th># of Documents</th>
					<th />
					<th />
				</tr>
			</thead>
			<tbody>
				{#each dataSources as dataSource}
					<DataSourceRow {dataSource} />
				{/each}
				{#if $query.hasNextPage}
					<tr>
						<td colspan="7">
							<button
								class="w-full btn btn-ghost"
								on:click={() => {
									$query.fetchNextPage();
								}}
							>
								Load More
							</button>
						</td>
					</tr>
				{/if}
			</tbody>
		</table>
	</div>
</div>
