// apps/website/src/components/bible/contents/ref.tsx
import { A } from '@solidjs/router';
import type { TextContent } from '@theaistudybible/core/types/bible';
import type { InferResponseType } from 'hono/client';
import { cn } from '~/lib/utils';
import type { RpcClient } from '~/types/rpc';

export default function RefContent({
  content,
  style,
  attrs,
  props,
  className,
  bible
}: {
  content: TextContent;
  style: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  attrs: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  props: any;
  className?: string;
  bible: InferResponseType<RpcClient['bibles'][':id']['$get']>['data'];
}) {
  const { loc } = attrs;
  const [bookAbbr, chapterAndVerse] = loc.split(' ');
  const [chapter, verse] = chapterAndVerse.split(':');
  let link = `/bible/${bible.abbreviation}/${bookAbbr}/${chapter}`;
  if (verse) {
    link += `/${verse}`;
  }
  return (
    <A
      id={content.id}
      data-type={content.type}
      data-verse-id={content.verseId}
      data-verse-number={content.verseNumber}
      {...props}
      className={cn(style, `hover:underline`, className)}
      href={link}
    >
      {content.text}
    </A>
  );
}

// apps/web/src/components/bible/reader/contents/ref.tsx
import { A } from '@solidjs/router';
import type { TextContent } from '@theaistudybible/core/types/bible';
import { createMemo } from 'solid-js';
import { useBibleReaderStore } from '~/components/providers/bible-reader';
import { cn } from '~/lib/utils';

export type RefContentProps = {
  content: TextContent;
  style: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  attrs: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  props: any;
  class?: string;
};

export default function RefContent(props: RefContentProps) {
  const [bibleReaderStore] = useBibleReaderStore();

  const link = createMemo(() => {
    const [bookAbbr, chapterAndVerse] = props.attrs.loc.split(' ');
    const [chapter, verse] = chapterAndVerse.split(':');
    let link = `/bible/${bibleReaderStore.bible!.abbreviation}/${bookAbbr}/${chapter}`;
    if (verse) {
      link += `/${verse}`;
    }
    return link;
  });

  return (
    <A
      id={props.content.id}
      data-type={props.content.type}
      data-verse-id={props.content.verseId}
      data-verse-number={props.content.verseNumber}
      {...props}
      class={cn(props.style, `hover:underline`, props.class)}
      href={link()}
    >
      {props.content.text}
    </A>
  );
}
