// apps/website/src/lib/components/bible/contents/contents.tsx
'use client';

import { cn } from '@/lib/utils';
import type { Routes } from '@/types/rpc';
import type { Content } from '@core/types/bible';
import type { InferResponseType } from 'hono/client';
import Link from 'next/link';
import CharContent from './char';
import NoteContent from './note';
import RefContent from './ref';
import TextContent from './text';

export default function Contents({
  bible,
  book,
  chapter,
  contents,
  highlights,
  className = ''
}: {
  bible: InferResponseType<Routes['bibles'][':id']['$get']>['data'];
  book: InferResponseType<Routes['bibles'][':id']['books'][':bookId']['$get']>['data'];
  chapter: InferResponseType<Routes['bibles'][':id']['chapters'][':chapterId']['$get']>['data'];
  contents: Content[];
  highlights?: {
    id: string;
    color: string;
  }[];
  className?: string;
}) {
  return (
    <>
      {contents.map((content) => {
        const { style, ...attrs } = content.attrs || {};
        const props = Object.entries(attrs).reduce(
          (acc, [key, value]) => {
            if (key.startsWith('data-')) {
              return {
                ...acc,
                [key]: value
              };
            }
            return {
              ...acc,
              [`data-${key}`]: value
            };
          },
          {} as Record<string, string>
        );

        switch (content.type) {
          case 'text': {
            return (
              <TextContent
                key={content.id}
                content={content}
                style={style}
                props={props}
                highlights={highlights}
                className={className}
              />
            );
          }
          case 'ref': {
            return (
              <RefContent
                key={content.id}
                content={content}
                style={style}
                attrs={attrs}
                props={props}
                className={className}
                bible={bible}
              />
            );
          }
          case 'verse': {
            return (
              <Link
                key={content.id}
                id={content.id}
                data-type={content.type}
                {...props}
                className={cn(style, 'hover:underline', className)}
                href={`/bible/${bible.abbreviation}/${book.abbreviation}/${chapter.number}/${content.number}`}
              >
                {content.number}
              </Link>
            );
          }
          case 'char': {
            return (
              <CharContent
                key={content.id}
                content={content}
                style={style}
                className={className}
                bible={bible}
                book={book}
                chapter={chapter}
                highlights={highlights}
                props={props}
              />
            );
          }
          case 'para': {
            return (
              <p
                key={content.id}
                id={content.id}
                data-type={content.type}
                {...props}
                className={cn(style, className)}
              >
                <Contents
                  bible={bible}
                  book={book}
                  chapter={chapter}
                  contents={content.contents}
                  highlights={highlights}
                />
              </p>
            );
          }
          case 'note': {
            return (
              <NoteContent
                key={content.id}
                bible={bible}
                book={book}
                chapter={chapter}
                content={content}
                highlights={highlights}
              />
            );
          }
          default: {
            console.error('Unknown content type', content);
            return null;
          }
        }
      })}
    </>
  );
}

// apps/website/src/lib/components/bible/contents/contents.svelte
<script lang="ts">
  import { A } from '$lib/components/ui/typeography';
  import type { RpcClient } from '$lib/types/rpc';
  import { cn } from '$lib/utils';
  import type { Content } from '@theaistudybible/core/types/bible';
  import type { InferResponseType } from 'hono/client';
  import CharContent from './char.svelte';
  import NoteContent from './note.svelte';
  import RefContent from './ref.svelte';
  import TextContent from './text.svelte';

  type Props = {
    bible: InferResponseType<RpcClient['bibles'][':id']['$get']>['data'];
    book: InferResponseType<RpcClient['bibles'][':id']['books'][':bookId']['$get']>['data'];
    chapter: InferResponseType<
      RpcClient['bibles'][':id']['chapters'][':chapterId']['$get']
    >['data'];
    contents: Content[];
    highlights?: {
      id: string;
      color: string;
    }[];
    class?: string;
  };

  let { bible, book, chapter, contents, highlights, class: className }: Props = $props();
</script>

{#each contents as content}
  {@const { style, ...attrs } = content.attrs || {}}
  {@const props = Object.entries(attrs).reduce(
    (acc, [key, value]) => {
      if (key.startsWith('data-')) {
        return {
          ...acc,
          [key]: value
        };
      }
      return {
        ...acc,
        [`data-${key}`]: value
      };
    },
    {} as Record<string, string>
  )}
  {#if content.type === 'text'}
    <TextContent {content} {style} {props} {highlights} class={className} />
  {:else if content.type === 'ref'}
    <RefContent {content} {style} {attrs} {props} class={className} {bible} />
  {:else if content.type === 'verse'}
    <A
      id={content.id}
      data-type={content.type}
      {...props}
      class={cn(style, 'hover:underline', className)}
      href={`/bible/${bible.abbreviation}/${book.abbreviation}/${chapter.number}/${content.number}`}
    >
      {content.number}
    </A>
  {:else if content.type === 'char'}
    <CharContent
      {content}
      {style}
      class={className}
      {bible}
      {book}
      {chapter}
      {highlights}
      {props}
    />
  {:else if content.type === 'para'}
    <p id={content.id} data-type={content.type} {...props} class={cn(style, className)}>
      <this {bible} {book} {chapter} contents={content.contents} {highlights}> </this>
    </p>
  {:else if content.type === 'note'}
    <NoteContent {bible} {book} {chapter} {content} {highlights} />
  {:else}
    <p>Unknown content type: {content.type}</p>
  {/if}
{/each}
